/* DO NOT EDIT. Generated by `cargo run --offline -p subscript-runtime --bin generate-host-header`.
 * Source of truth: runtime/src/ffi.rs and runtime/src/context.rs.
 */
#ifndef SUBSCRIPT_RUNTIME_H
#define SUBSCRIPT_RUNTIME_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct Context Context;

/**
 * Host callback invoked when a Context records its first trap.
 *
 * The callback deliberately receives no [`Context`] handle. It runs
 * inside [`Context::trap`] while that method holds exclusive access to
 * the Context, so calling any `sub_rt_*` API that takes that Context
 * (including through a pointer smuggled in `userdata`) would violate
 * Rust's aliasing rules and is undefined behaviour.
 *
 * `message` points into the stored [`TrapRecord`]. The bytes remain
 * valid after the callback returns, until the trap is cleared or the
 * Context is released.
 */
typedef void (*sub_rt_trap_observer)(void* userdata, uint32_t kind, uint32_t pos_id, const uint8_t* message, uint64_t message_len);

/**
 * Host callback invoked for each line printed while it is installed.
 *
 * The callback receives no [`Context`] handle. It runs inside
 * [`Context::print_line`] while that method holds exclusive access to the
 * Context, so calling any `sub_rt_*` API that takes that Context
 * (including through a pointer smuggled in `userdata`) would violate
 * Rust's aliasing rules and is undefined behaviour.
 *
 * `line` excludes the trailing newline and is valid only for the duration
 * of the callback.
 */
typedef void (*sub_rt_print_observer)(void* userdata, const uint8_t* line, uint64_t line_len);

/**
 * Host callback invoked once for each live Context allocation.
 *
 * `payload_bytes` follows the same tier policy as
 * [`Context::live_bytes`]: exact requested bytes in the development
 * tier and for ship-tier large allocations, size-class payload capacity
 * for ship-tier arena blocks.
 */
typedef void (*sub_rt_alloc_visitor)(void* userdata, uint32_t class_id, uint32_t pos_id, uint64_t payload_bytes);

/**
 * C calling convention shared by the module initializer (`ss_init`) and every
 * supported host export.
 *
 * A host that may clear traps brackets each call with
 * `sub_rt_ctx_enter_script` and `sub_rt_ctx_exit_script`.
 *
 * An ordinary run entry uses `ss_export_main`; a host-owned entry may instead
 * drive other zero-argument `void` exports using the symbol
 * `ss_export_<name>` and this same C signature.
 */
typedef void (*sub_script_main_entry)(Context* ctx);

/* Every linked program defines ss_init. A program with an exported main
 * defines ss_export_main; every other currently supported host export is
 * named `ss_export_<name>` with the same signature. */
void ss_init(Context* ctx);
void ss_export_main(Context* ctx);

int32_t sub_rt_ctx_clear_trap(Context* ctx);
void sub_rt_ctx_enter_script(Context* ctx);
void sub_rt_ctx_exit_script(Context* ctx);
void sub_rt_ctx_fail_alloc_after(Context* ctx, uint64_t n);
uint64_t sub_rt_ctx_live_allocations(const Context* ctx);
uint64_t sub_rt_ctx_live_bytes(const Context* ctx);
Context* sub_rt_ctx_new(void);
void sub_rt_ctx_release(Context* ctx);
uint64_t sub_rt_ctx_reserved_bytes(const Context* ctx);
void sub_rt_ctx_seed_random(Context* ctx, uint64_t seed);
/**
 * Enables or disables freed-handle diagnostics for this Context.
 *
 * When enabled, dangling-handle use and double free can be detected, but
 * freed allocations are retained until Context release, so memory can
 * grow without bound. The setting is disabled by default.
 *
 * This must be called before the first allocation. Returns 1 when the
 * setting was applied, or 0 when allocation had already started and the
 * setting was left unchanged.
 *
 * # Safety
 *
 * `ctx` follows the exclusive Context contract.
 */
int32_t sub_rt_ctx_set_freed_handle_diagnostics(Context* ctx, uint32_t enabled);
void sub_rt_ctx_set_now(Context* ctx, int64_t ms);
/**
 * Installs the callback invoked for each line printed by `ctx`. Passing a
 * null `observer` clears it.
 *
 * While set, the callback receives each line without its trailing newline
 * and the Context stdout sink retains none of that line's bytes. The line
 * is valid only for the duration of the callback.
 *
 * The callback receives no Context handle. It runs from inside
 * [`Context::print_line`] while the Context is exclusively borrowed, so it
 * must not call any `sub_rt_*` function taking that Context (including by
 * recovering the pointer from `userdata`); doing so is an aliasing
 * violation and undefined behaviour.
 *
 * # Safety
 *
 * `ctx` follows the exclusive Context contract. `observer`, when present,
 * must be callable with `userdata` and obey the no-re-entry rule above.
 */
void sub_rt_ctx_set_print_observer(Context* ctx, sub_rt_print_observer observer, void* userdata);
void sub_rt_ctx_set_regex_budget(Context* ctx, uint64_t budget);
void sub_rt_ctx_set_trap_observer(Context* ctx, sub_rt_trap_observer observer, void* userdata);
const uint8_t* sub_rt_ctx_stdout(const Context* ctx, uint64_t* len);
uint32_t sub_rt_ctx_trap_kind(const Context* ctx);
const uint8_t* sub_rt_ctx_trap_message(const Context* ctx, uint64_t* len);
uint32_t sub_rt_ctx_trap_pos_id(const Context* ctx);
uint64_t sub_rt_ctx_visit_live_allocations(const Context* ctx, sub_rt_alloc_visitor visitor, void* userdata);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* SUBSCRIPT_RUNTIME_H */
