/* DO NOT EDIT. Generated by `cargo run --offline -p subscript-runtime --bin generate-host-header`.
 * Source of truth: runtime/src/ffi.rs and runtime/src/context.rs.
 */
#ifndef SUBSCRIPT_RUNTIME_H
#define SUBSCRIPT_RUNTIME_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct Context Context;

/**
 * Host callback invoked when a Context records its first trap.
 *
 * The callback deliberately receives no [`Context`] handle. It runs
 * inside [`Context::trap`] while that method holds exclusive access to
 * the Context, so calling any `sub_rt_*` API that takes that Context
 * (including through a pointer smuggled in `userdata`) would violate
 * Rust's aliasing rules and is undefined behaviour.
 *
 * `message` points into the stored [`TrapRecord`]. The bytes remain
 * valid after the callback returns, until the trap is cleared or the
 * Context is released.
 */
typedef void (*sub_rt_trap_observer)(void* userdata, uint32_t kind, uint32_t pos_id, const uint8_t* message, uint64_t message_len);

/**
 * C calling convention shared by the module initializer (`ss_init`)
 * and the required exported `main(): void` (`ss_export_main`).
 *
 * A host that may clear traps brackets each call with
 * `sub_rt_ctx_enter_script` and `sub_rt_ctx_exit_script`.
 *
 * Every other currently supported host export is a zero-argument
 * `void` script function using the symbol `ss_export_<name>` and this
 * same C signature.
 */
typedef void (*sub_script_main_entry)(Context* ctx);

/* Every linked program defines these two entry symbols. Every other
 * currently supported host export is a zero-argument void function
 * named `ss_export_<name>` with the same signature. */
void ss_init(Context* ctx);
void ss_export_main(Context* ctx);

int32_t sub_rt_ctx_clear_trap(Context* ctx);
void sub_rt_ctx_enter_script(Context* ctx);
void sub_rt_ctx_exit_script(Context* ctx);
uint64_t sub_rt_ctx_live_allocations(const Context* ctx);
uint64_t sub_rt_ctx_live_bytes(const Context* ctx);
Context* sub_rt_ctx_new(void);
void sub_rt_ctx_release(Context* ctx);
uint64_t sub_rt_ctx_reserved_bytes(const Context* ctx);
void sub_rt_ctx_seed_random(Context* ctx, uint64_t seed);
void sub_rt_ctx_set_now(Context* ctx, int64_t ms);
void sub_rt_ctx_set_trap_observer(Context* ctx, sub_rt_trap_observer observer, void* userdata);
const uint8_t* sub_rt_ctx_stdout(const Context* ctx, uint64_t* len);
uint32_t sub_rt_ctx_trap_kind(const Context* ctx);
const uint8_t* sub_rt_ctx_trap_message(const Context* ctx, uint64_t* len);
uint32_t sub_rt_ctx_trap_pos_id(const Context* ctx);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* SUBSCRIPT_RUNTIME_H */
