/* DO NOT EDIT. Generated by `cargo run --offline -p subscript-runtime --bin generate-host-header`.
 * Source of truth: runtime/src/ffi.rs, runtime/src/context.rs, and runtime/src/worker.rs.
 */
#ifndef SUBSCRIPT_RUNTIME_H
#define SUBSCRIPT_RUNTIME_H

#include <stdint.h>

/* Recommended freed-handle diagnostics retention budget. The runtime does
 * not treat this value specially. */
#define SUBSCRIPT_RT_FREED_HANDLE_DIAGNOSTICS_DEFAULT_MAX_RETAINED_BYTES UINT64_C(1073741824)

/* Diagnostics advisory kinds. */
#define SUBSCRIPT_RT_DIAGNOSTICS_ADVISORY_CALLBACK_USERDATA_FREE UINT32_C(1)
#define SUBSCRIPT_RT_DIAGNOSTICS_ADVISORY_BINDING_COUNT UINT32_C(2)

#ifdef __cplusplus
extern "C" {
#endif

typedef struct subscript_rt_context subscript_rt_context;

typedef struct subscript_rt_worker subscript_rt_worker;
typedef struct subscript_rt_worker_inbox subscript_rt_worker_inbox;
typedef struct subscript_rt_worker_outbox subscript_rt_worker_outbox;

typedef struct subscript_rt_worker_message_descriptor {
    uint64_t payload_size;
    uint64_t string_slot_count;
    const uint64_t* string_slot_offsets;
} subscript_rt_worker_message_descriptor;

/**
 * Host callback invoked when a subscript_rt_context records its first trap.
 *
 * The callback deliberately receives no [`subscript_rt_context`] handle. It runs
 * inside [`subscript_rt_context::trap`] while that method holds exclusive access to
 * the subscript_rt_context, so calling any `subscript_rt_*` API that takes that subscript_rt_context
 * (including through a pointer smuggled in `userdata`) would violate
 * Rust's aliasing rules and is undefined behaviour.
 *
 * `message` points into the stored [`TrapRecord`]. The bytes remain
 * valid after the callback returns, until the trap is cleared or the
 * subscript_rt_context is released.
 */
typedef void (*subscript_rt_trap_observer)(void* userdata, uint32_t kind, uint32_t pos_id, const uint8_t* message, uint64_t message_len);

/**
 * Host callback invoked for each line printed while it is installed.
 *
 * The callback receives no [`subscript_rt_context`] handle. It runs inside
 * [`subscript_rt_context::print_line`] while that method holds exclusive access to the
 * subscript_rt_context, so calling any `subscript_rt_*` API that takes that subscript_rt_context
 * (including through a pointer smuggled in `userdata`) would violate
 * Rust's aliasing rules and is undefined behaviour.
 *
 * `line` excludes the trailing newline and is valid only for the duration
 * of the callback.
 */
typedef void (*subscript_rt_print_observer)(void* userdata, const uint8_t* line, uint64_t line_len);

/**
 * Host callback invoked for optional runtime diagnostics advisories.
 *
 * The callback deliberately receives no [`subscript_rt_context`] handle. It runs while
 * the subscript_rt_context is exclusively borrowed, so calling any `subscript_rt_*` API
 * that takes that subscript_rt_context (including through a pointer smuggled in
 * `userdata`) would violate Rust's aliasing rules and is undefined
 * behaviour. The callback is observation-only and must not call back into
 * script.
 *
 * `message` is valid only for the duration of the callback.
 */
typedef void (*subscript_rt_diagnostics_observer)(void* userdata, uint32_t kind, uint32_t pos_id, const uint8_t* message, uint64_t message_len);

/**
 * Host callback invoked once for each live subscript_rt_context allocation.
 *
 * `payload_bytes` follows the same tier policy as
 * [`subscript_rt_context::live_bytes`]: exact requested bytes in the development
 * tier and for ship-tier large allocations, size-class payload capacity
 * for ship-tier arena blocks.
 */
typedef void (*subscript_rt_alloc_visitor)(void* userdata, uint32_t class_id, uint32_t pos_id, uint64_t payload_bytes);

/**
 * C calling convention shared by the module initializer (`subscript_init`) and every
 * supported host export.
 *
 * A host that may clear traps brackets each call with
 * `subscript_rt_ctx_enter_script` and `subscript_rt_ctx_exit_script`.
 *
 * An ordinary run entry uses `subscript_export_main`; a host-owned entry may instead
 * drive other zero-argument `void` exports using the symbol
 * `subscript_export_<name>` and this same C signature.
 */
typedef void (*subscript_main_entry)(subscript_rt_context* ctx);

/**
 * Initializer called on a newly created worker subscript_rt_context before its entry.
 */
typedef void (*subscript_rt_worker_init)(subscript_rt_context* ctx);

/**
 * Entry called on a worker thread with its dedicated subscript_rt_context and endpoints.
 */
typedef void (*subscript_rt_worker_entry)(subscript_rt_context* ctx, subscript_rt_worker_inbox* inbox, subscript_rt_worker_outbox* outbox);

/* Every linked program defines subscript_init. A program with an exported main
 * defines subscript_export_main. Each host-callable export is synchronous, returns
 * void, and takes only sized numerics, booleans, or opaque handles. A zero-argument
 * void async export is also host-callable. Its symbol is `subscript_export_<name>`
 * with the same signature. */
void subscript_init(subscript_rt_context* ctx);
void subscript_export_main(subscript_rt_context* ctx);

/**
 * Returns the number of suspended async root invocations owned by `ctx`.
 *
 * # Safety
 *
 * `ctx` follows the shared subscript_rt_context contract.
 */
uint64_t subscript_rt_ctx_async_pending(const subscript_rt_context* ctx);
/**
 * Resumes every root pending at call entry exactly once, in host kick
 * order, and returns the number still pending. On a trapped subscript_rt_context this
 * is a no-op returning the current count; an empty subscript_rt_context returns zero.
 *
 * # Safety
 *
 * `ctx` follows the exclusive subscript_rt_context contract. Generated code for every
 * pending root remains linked and callable.
 */
uint64_t subscript_rt_ctx_async_step(subscript_rt_context* ctx);
int32_t subscript_rt_ctx_clear_trap(subscript_rt_context* ctx);
void subscript_rt_ctx_enter_script(subscript_rt_context* ctx);
void subscript_rt_ctx_exit_script(subscript_rt_context* ctx);
void subscript_rt_ctx_fail_alloc_after(subscript_rt_context* ctx, uint64_t n);
uint64_t subscript_rt_ctx_live_allocations(const subscript_rt_context* ctx);
uint64_t subscript_rt_ctx_live_bytes(const subscript_rt_context* ctx);
subscript_rt_context* subscript_rt_ctx_new(void);
void subscript_rt_ctx_release(subscript_rt_context* ctx);
uint64_t subscript_rt_ctx_reserved_bytes(const subscript_rt_context* ctx);
void subscript_rt_ctx_seed_random(subscript_rt_context* ctx, uint64_t seed);
/**
 * Sets the callback-binding count advisory threshold.
 *
 * Whenever a new callback binding is interned and the resulting count is at
 * least `threshold`, the installed diagnostics observer receives
 * `SUBSCRIPT_RT_DIAGNOSTICS_ADVISORY_BINDING_COUNT`, position id zero, and a
 * message carrying the count and threshold. Re-registering an existing
 * binding identity never advises.
 *
 * The threshold has literal semantics: zero advises on the first record.
 * The default is `UINT64_MAX`. With the default threshold or no diagnostics
 * observer, the check retains no event or message state.
 *
 * # Safety
 *
 * `ctx` follows the exclusive subscript_rt_context contract.
 */
void subscript_rt_ctx_set_binding_count_advisory(subscript_rt_context* ctx, uint64_t threshold);
/**
 * Installs the observation-only callback invoked for optional runtime
 * diagnostics advisories. Passing a null `observer` clears it.
 *
 * The first advisory kind is
 * `SUBSCRIPT_RT_DIAGNOSTICS_ADVISORY_CALLBACK_USERDATA_FREE`: immediately
 * before an explicit free releases an address held in either userdata slot
 * of a live callback binding. Freeing such userdata is legal;
 * the advisory does not trap, cancel, or otherwise change the release.
 *
 * `SUBSCRIPT_RT_DIAGNOSTICS_ADVISORY_BINDING_COUNT` reports each newly
 * interned callback binding at or above the host-configured count threshold;
 * its position id is zero and its message carries the count and threshold.
 *
 * The callback receives no subscript_rt_context handle. It runs while the subscript_rt_context is
 * exclusively borrowed, so it must not call any `subscript_rt_*` function
 * taking that subscript_rt_context (including by recovering the pointer from `userdata`);
 * doing so is an aliasing violation and undefined behaviour. It must not
 * call back into script. The message is valid only for the duration of the
 * callback.
 *
 * With no observer installed (the default), explicit frees skip the
 * registered-binding check entirely.
 *
 * # Safety
 *
 * `ctx` follows the exclusive subscript_rt_context contract. `observer`, when present,
 * must be callable with `userdata` and obey the no-re-entry rule above.
 */
void subscript_rt_ctx_set_diagnostics_observer(subscript_rt_context* ctx, subscript_rt_diagnostics_observer observer, void* userdata);
/**
 * Enables or disables freed-handle diagnostics for this subscript_rt_context.
 *
 * When enabled, freed allocations whose requested payload is at least
 * `min_payload_bytes` are retained within `max_retained_bytes` of layout
 * storage. When a new retained allocation would exceed that budget, the
 * oldest retained allocations are evicted and released first. Memory held
 * by the mode is bounded by `max_retained_bytes`.
 *
 * Dangling-handle and double-free diagnostics are guaranteed for the most
 * recently retained frees whose layouts fit the budget, within the class
 * covered by the threshold, and best-effort otherwise. Freeing a pointer
 * the subscript_rt_context never owned still traps regardless of the threshold or
 * budget. A zero threshold covers every payload; a zero budget retains
 * nothing. `UINT64_MAX` is effectively unbounded. `min_payload_bytes` and
 * `max_retained_bytes` are ignored when `enabled` is 0.
 * The setting is disabled by default.
 *
 * This must be called before the first allocation. Returns 1 when the
 * setting was applied, or 0 when allocation had already started and the
 * setting was left unchanged.
 *
 * # Safety
 *
 * `ctx` follows the exclusive subscript_rt_context contract.
 */
int32_t subscript_rt_ctx_set_freed_handle_diagnostics(subscript_rt_context* ctx, uint32_t enabled, uint64_t min_payload_bytes, uint64_t max_retained_bytes);
void subscript_rt_ctx_set_now(subscript_rt_context* ctx, int64_t ms);
/**
 * Installs the callback invoked for each line printed by `ctx`. Passing a
 * null `observer` clears it.
 *
 * While set, the callback receives each line without its trailing newline
 * and the subscript_rt_context stdout sink retains none of that line's bytes. The line
 * is valid only for the duration of the callback.
 *
 * The callback receives no subscript_rt_context handle. It runs from inside
 * [`subscript_rt_context::print_line`] while the subscript_rt_context is exclusively borrowed, so it
 * must not call any `subscript_rt_*` function taking that subscript_rt_context (including by
 * recovering the pointer from `userdata`); doing so is an aliasing
 * violation and undefined behaviour.
 *
 * # Safety
 *
 * `ctx` follows the exclusive subscript_rt_context contract. `observer`, when present,
 * must be callable with `userdata` and obey the no-re-entry rule above.
 */
void subscript_rt_ctx_set_print_observer(subscript_rt_context* ctx, subscript_rt_print_observer observer, void* userdata);
void subscript_rt_ctx_set_regex_budget(subscript_rt_context* ctx, uint64_t budget);
void subscript_rt_ctx_set_trap_observer(subscript_rt_context* ctx, subscript_rt_trap_observer observer, void* userdata);
const uint8_t* subscript_rt_ctx_stdout(const subscript_rt_context* ctx, uint64_t* len);
uint32_t subscript_rt_ctx_trap_kind(const subscript_rt_context* ctx);
const uint8_t* subscript_rt_ctx_trap_message(const subscript_rt_context* ctx, uint64_t* len);
uint32_t subscript_rt_ctx_trap_pos_id(const subscript_rt_context* ctx);
uint64_t subscript_rt_ctx_visit_live_allocations(const subscript_rt_context* ctx, subscript_rt_alloc_visitor visitor, void* userdata);

/**
 * Closes a worker's parent-to-worker queue.
 *
 * Already queued messages remain receivable. After they are drained, worker
 * inbox receives observe end-of-input as a null result. The operation is
 * idempotent.
 *
 * # Safety
 *
 * `parent` follows the exclusive subscript_rt_context contract and `worker` belongs to it.
 */
void subscript_rt_worker_close(subscript_rt_context* parent, subscript_rt_worker* worker);
/**
 * Non-blockingly receives one parent-to-worker message.
 *
 * A message is copied into a fresh allocation owned by the worker `ctx`.
 * Null means no queued message, closed-and-drained input, or a trap.
 *
 * # Safety
 *
 * `ctx` is the current worker's exclusive subscript_rt_context and `inbox` is the live
 * endpoint passed to that worker's entry.
 */
uint8_t* subscript_rt_worker_inbox_poll(subscript_rt_context* ctx, subscript_rt_worker_inbox* inbox);
/**
 * Blocks until one parent-to-worker message or end-of-input is available.
 *
 * A message is copied into a fresh allocation owned by the worker `ctx`.
 * Null reports closed-and-drained input or a trap. The blocking path sleeps
 * on an OS condition variable and never spins.
 *
 * # Safety
 *
 * `ctx` is the current worker's exclusive subscript_rt_context and `inbox` is the live
 * endpoint passed to that worker's entry.
 */
uint8_t* subscript_rt_worker_inbox_wait(subscript_rt_context* ctx, subscript_rt_worker_inbox* inbox);
/**
 * Joins a worker thread, blocking until its entry and subscript_rt_context teardown end.
 *
 * Returns 1 for a clean worker. If the worker subscript_rt_context trapped, this returns 0
 * and records trap kind 22 (`worker-trapped`) on the joining subscript_rt_context. Joining
 * an already joined worker repeats its recorded outcome.
 *
 * # Safety
 *
 * `parent` follows the exclusive subscript_rt_context contract and `worker` belongs to it.
 */
int32_t subscript_rt_worker_join(subscript_rt_context* parent, subscript_rt_worker* worker);
/**
 * Copies one fixed-size payload into the worker-to-parent queue.
 *
 * Posting never blocks. Returns 1 when accepted and 0 when the endpoint or
 * subscript_rt_context is no longer usable.
 *
 * # Safety
 *
 * `ctx` is the current worker's exclusive subscript_rt_context, `outbox` is its live
 * endpoint, and `payload` points to the output payload size supplied at
 * spawn (or is null only when that size is zero).
 */
int32_t subscript_rt_worker_outbox_post(subscript_rt_context* ctx, subscript_rt_worker_outbox* outbox, const uint8_t* payload);
/**
 * Non-blockingly receives one worker-to-parent message.
 *
 * A message is copied into a fresh allocation owned by `parent` and that
 * allocation is returned. Null means that no message is currently queued,
 * the output is closed and drained, or the subscript_rt_context trapped while allocating.
 *
 * # Safety
 *
 * `parent` follows the exclusive subscript_rt_context contract and `worker` belongs to it.
 */
uint8_t* subscript_rt_worker_poll(subscript_rt_context* parent, subscript_rt_worker* worker);
/**
 * Copies one fixed-size payload into a worker's parent-to-worker queue.
 *
 * Posting never blocks. Returns 1 when accepted and 0 when the worker input
 * is closed or the subscript_rt_context is trapped.
 *
 * # Safety
 *
 * `parent` follows the exclusive subscript_rt_context contract; `worker` belongs to it.
 * `payload` points to the input payload size supplied at spawn (and may be
 * null only when that size is zero).
 */
int32_t subscript_rt_worker_post(subscript_rt_context* parent, subscript_rt_worker* worker, const uint8_t* payload);
/**
 * Spawns a runtime-owned OS thread with a fresh dedicated subscript_rt_context.
 *
 * The worker thread calls `init`, then calls `entry` with its subscript_rt_context and
 * worker-side endpoints unless initialization trapped. `input_descriptor`
 * describes messages accepted by [`subscript_rt_worker_post`], and
 * `output_descriptor` describes messages accepted by
 * [`subscript_rt_worker_outbox_post`]. Both queues are unbounded byte-copy
 * queues. The runtime copies both descriptors during this call. The returned
 * handle is owned by `parent` and remains valid until that subscript_rt_context is
 * released. Null is returned after a parent trap when a callback or
 * descriptor is invalid, or thread creation fails.
 *
 * # Safety
 *
 * `parent` follows the exclusive subscript_rt_context contract. `init` and `entry` must
 * be linked C-callable functions that obey the runtime trap discipline and
 * remain callable until the worker is joined. Both descriptors and their
 * offset arrays must be readable for this call.
 */
subscript_rt_worker* subscript_rt_worker_spawn(subscript_rt_context* parent, subscript_rt_worker_init init, subscript_rt_worker_entry entry, const subscript_rt_worker_message_descriptor* input_descriptor, const subscript_rt_worker_message_descriptor* output_descriptor);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* SUBSCRIPT_RUNTIME_H */
