//! The `offsetof` layout proof (`specs/blocks/compiler.md` §12.3, scaled to
//! production complexity at §13.4): design invariant 1 (C-ABI-identical
//! struct layout) is machine-verified here, not asserted.
//!
//! For every struct in the synthetic header (`corpus/interop/interop.h`)
//! that has a language `@value class` equivalent, this test compares the
//! language compiler's computed layout — total `size`, `align`, and each
//! field's byte offset, via the public [`value_class_layouts`] API —
//! against the platform C compiler's `sizeof` / `_Alignof` / `offsetof`
//! for the real C struct. A mismatch on any field, size, or alignment
//! fails the test. The set spans dozens of structs (§13.4) mixing varied
//! scalar/padding, nested by-value structs, flag-typedef fields, intrusive
//! chains, string-view / array-pair descriptors, and descriptor-embedded
//! arrays — the production-scale discharge of the C-ABI-identity claim.
//!
//! The language-side value classes below are **hand-authored**. Pointer-
//! shaped C fields (raw pointers, `size_t`, opaque handles, function
//! pointers, flag typedefs) are modeled here as `u64`, the sized numeric
//! with the same 8-byte size and alignment on every dev target; the
//! generated mirror substitutes the boundary forms (`X | null`, branded
//! handles, `string`, flag aliases) whose lowered layout is identical, so
//! this proof carries over unchanged. A descriptor-embedded `(count,
//! pointer)` array is modeled by its raw C pair layout — the layout both
//! tiers marshal — since the mirror collapses it to a single `T[]` field.
//!
//! A missing C compiler is a **failure, not a skip**, consistent with the
//! standing gate's discipline (§11): the gate machine is the development
//! machine.

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::process::Command;

use subscript_codegen::value_class_layouts;
use subscript_compiler::{check_program, SourceFile};

/// The language-side value-class mirror of every mirrorable struct in
/// `corpus/interop/interop.h`. Field names and declaration order match
/// the C header exactly so offsets line up field-by-field. Pointer /
/// `size_t` / handle / function-pointer C fields are modeled as `u64`
/// (identical 8/8 layout); see the module comment. Hand-authored for
/// P5.1; regenerated by the mirror generator at P5.2.
const MIRROR_SOURCE: &str = r#"
enum SubChainKind {
  Base = 0,
  ExtA = 1,
  ExtB = 2,
}

@value
class SubChainHeader {
  sType: SubChainKind;
  next: u64;
}

@value
class SubChainExtA {
  header: SubChainHeader;
  intensity: f32;
  flags: u32;
}

@value
class SubChainExtB {
  header: SubChainHeader;
  scale: f64;
  level: i32;
}

@value
class SubBufferView {
  items: u64;
  count: u64;
}

@value
class SubStringView {
  data: u64;
  len: u64;
}

@value
class SubCallbackInfo {
  callback: u64;
  userdata: u64;
  userparam: u64;
}

@value
class SubTransform {
  basis: FixedArray<f32, 16>;
  bone: i32;
  weight: f64;
  visible: boolean;
}

@value
class SubSample {
  a: boolean;
  b: f64;
  c: i32;
  d: f32;
}

// ---- P6.3 production-scale additions (compiler.md §13.4) --------------
// Dozens of structs mixing varied scalar/padding, nested by-value structs,
// flag-typedef fields (SubAccess -> u64), intrusive chains, string-view /
// array-pair descriptors, and descriptor-embedded arrays. Pointer / size_t
// / flag / callback fields are modeled as u64 (identical 8/8 layout); a
// descriptor-embedded array is modeled by its RAW C pair layout (count then
// pointer), the layout both tiers marshal. Nested structs are declared
// before their users.

// Typed (pointer, count) slice descriptors (a31): each a 16-byte pair.
@value
class SubSliceF32 {
  items: u64;
  count: u64;
}

@value
class SubSliceI32 {
  items: u64;
  count: u64;
}

@value
class SubSliceF64 {
  items: u64;
  count: u64;
}

@value
class SubSliceI64 {
  items: u64;
  count: u64;
}

// Varied scalar / padding layouts.
@value
class SubVec2 {
  x: f32;
  y: f32;
}

@value
class SubVec3 {
  x: f32;
  y: f32;
  z: f32;
}

@value
class SubVec4 {
  x: f32;
  y: f32;
  z: f32;
  w: f32;
}

@value
class SubRect {
  x: i32;
  y: i32;
  width: u32;
  height: u32;
}

@value
class SubRange {
  offset: u64;
  size: u64;
}

@value
class SubColor {
  r: f32;
  g: f32;
  b: f32;
  a: f32;
}

@value
class SubTimings {
  cpu: f64;
  gpu: f64;
  frame: i32;
}

@value
class SubMixed {
  enabled: boolean;
  id: i64;
  visible: boolean;
  ratio: f32;
}

@value
class SubPadB {
  head: i32;
  mid: boolean;
  tail: f64;
}

// Nested by-value structs.
@value
class SubExtent {
  width: u32;
  height: u32;
  depth: u32;
}

@value
class SubImageInfo {
  extent: SubExtent;
  mipLevels: u32;
  usage: u64;
}

@value
class SubBounds {
  min: SubVec3;
  max: SubVec3;
}

@value
class SubViewport {
  rect: SubRect;
  depth: SubRange;
}

@value
class SubNodeInfo {
  bounds: SubBounds;
  id: u32;
  tint: SubColor;
}

// Intrusive chains: the common header embedded first.
@value
class SubChainExtC {
  header: SubChainHeader;
  offset: SubVec3;
  flags: u32;
}

@value
class SubChainExtD {
  header: SubChainHeader;
  scale: f64;
  level: i64;
  active: boolean;
}

@value
class SubEventHeader {
  kind: i32;
  next: u64;
}

@value
class SubEventKey {
  header: SubEventHeader;
  code: u32;
  pressed: boolean;
}

@value
class SubEventMove {
  header: SubEventHeader;
  dx: f32;
  dy: f32;
}

// Flag-typedef fields (SubAccess -> u64).
@value
class SubPassInfo {
  access: u64;
  width: u32;
  height: u32;
}

@value
class SubResourceDesc {
  usage: u64;
  range: SubRange;
  count: u32;
}

// Descriptor-embedded (count, pointer) arrays — modeled by their raw C pair
// layout (the mirror collapses them to `T[]`, but both tiers marshal this).
@value
class SubDrawList {
  layer: u32;
  drawsCount: u64;
  draws: u64;
}

@value
class SubCommandBuffer {
  queue: u32;
  commandsCount: u64;
  commands: u64;
}

// Callback-info (fn pointer + userdata) — two 8-byte pointer slots.
@value
class SubCompletionInfo {
  callback: u64;
  userdata: u64;
}

export function main(): void {}
"#;

/// The mirrored structs, each as (C typedef name == language class name,
/// field names in declaration order). Drives both the generated C probe
/// and the comparison, so both sides read the same field list.
fn mirrored_structs() -> Vec<(&'static str, Vec<&'static str>)> {
    vec![
        ("SubChainHeader", vec!["sType", "next"]),
        ("SubChainExtA", vec!["header", "intensity", "flags"]),
        ("SubChainExtB", vec!["header", "scale", "level"]),
        ("SubBufferView", vec!["items", "count"]),
        ("SubStringView", vec!["data", "len"]),
        ("SubCallbackInfo", vec!["callback", "userdata", "userparam"]),
        ("SubTransform", vec!["basis", "bone", "weight", "visible"]),
        ("SubSample", vec!["a", "b", "c", "d"]),
        // P6.3 production-scale additions (§13.4).
        ("SubSliceF32", vec!["items", "count"]),
        ("SubSliceI32", vec!["items", "count"]),
        ("SubSliceF64", vec!["items", "count"]),
        ("SubSliceI64", vec!["items", "count"]),
        ("SubVec2", vec!["x", "y"]),
        ("SubVec3", vec!["x", "y", "z"]),
        ("SubVec4", vec!["x", "y", "z", "w"]),
        ("SubRect", vec!["x", "y", "width", "height"]),
        ("SubRange", vec!["offset", "size"]),
        ("SubColor", vec!["r", "g", "b", "a"]),
        ("SubTimings", vec!["cpu", "gpu", "frame"]),
        ("SubMixed", vec!["enabled", "id", "visible", "ratio"]),
        ("SubPadB", vec!["head", "mid", "tail"]),
        ("SubExtent", vec!["width", "height", "depth"]),
        ("SubImageInfo", vec!["extent", "mipLevels", "usage"]),
        ("SubBounds", vec!["min", "max"]),
        ("SubViewport", vec!["rect", "depth"]),
        ("SubNodeInfo", vec!["bounds", "id", "tint"]),
        ("SubChainExtC", vec!["header", "offset", "flags"]),
        ("SubChainExtD", vec!["header", "scale", "level", "active"]),
        ("SubEventHeader", vec!["kind", "next"]),
        ("SubEventKey", vec!["header", "code", "pressed"]),
        ("SubEventMove", vec!["header", "dx", "dy"]),
        ("SubPassInfo", vec!["access", "width", "height"]),
        ("SubResourceDesc", vec!["usage", "range", "count"]),
        ("SubDrawList", vec!["layer", "drawsCount", "draws"]),
        ("SubCommandBuffer", vec!["queue", "commandsCount", "commands"]),
        ("SubCompletionInfo", vec!["callback", "userdata"]),
    ]
}

/// C-side layout truth for one struct: size, alignment, and each field's
/// byte offset in declaration order.
#[derive(Debug, PartialEq, Eq)]
struct CLayout {
    size: u32,
    align: u32,
    field_offsets: Vec<(String, u32)>,
}

/// The synthetic header's directory (`corpus/interop/`), resolved from
/// this crate's manifest so nothing outside the repository is referenced.
fn header_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../corpus/interop")
}

/// Finds `name` on `PATH`, returning its full path when an executable
/// file exists. On Windows the `.exe` extension is tried as well.
fn find_on_path(name: &str) -> Option<PathBuf> {
    let path = std::env::var_os("PATH")?;
    let exts: &[&str] = if cfg!(windows) { &["", ".exe"] } else { &[""] };
    for dir in std::env::split_paths(&path) {
        for ext in exts {
            let cand = dir.join(format!("{name}{ext}"));
            if cand.is_file() {
                return Some(cand);
            }
        }
    }
    None
}

/// Resolves the C compiler: clang (compiler.md §11). `$CC` verbatim when
/// set, else `clang` on `PATH`, else — on Windows only — the standard
/// LLVM install (`%ProgramFiles%\LLVM\bin\clang.exe`). Falls back to the
/// bare name `clang`, so a missing toolchain fails with a clear message.
fn host_c_compiler() -> std::ffi::OsString {
    if let Some(cc) = std::env::var_os("CC") {
        return cc;
    }
    if let Some(p) = find_on_path("clang") {
        return p.into_os_string();
    }
    #[cfg(windows)]
    if let Some(pf) = std::env::var_os("ProgramFiles") {
        let llvm = PathBuf::from(pf).join("LLVM").join("bin").join("clang.exe");
        if llvm.is_file() {
            return llvm.into_os_string();
        }
    }
    "clang".into()
}

/// A temporary working directory, removed on drop.
struct TempDir {
    path: PathBuf,
}

impl TempDir {
    fn new() -> TempDir {
        use std::sync::atomic::{AtomicU64, Ordering};
        static COUNTER: AtomicU64 = AtomicU64::new(0);
        let n = COUNTER.fetch_add(1, Ordering::Relaxed);
        let path = std::env::temp_dir().join(format!(
            "subscript-offsetof-{}-{}",
            std::process::id(),
            n
        ));
        std::fs::create_dir_all(&path).expect("create temp dir");
        TempDir { path }
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.path);
    }
}

/// Emits a C probe that `#include`s the synthetic header and prints, for
/// every mirrored struct, `sizeof`, `_Alignof`, and `offsetof` of each
/// field; compiles it with the platform C compiler and runs it; parses
/// the numbers back into a per-struct [`CLayout`].
///
/// Every failure here (compiler absent, compile error, run error,
/// unparseable output) panics: a missing or broken C compiler fails the
/// test, it does not skip it (§11).
fn c_truth(structs: &[(&'static str, Vec<&'static str>)]) -> BTreeMap<String, CLayout> {
    let mut body = String::new();
    body.push_str("#include \"interop.h\"\n");
    body.push_str("#include <stddef.h>\n");
    body.push_str("#include <stdio.h>\n");
    body.push_str("int main(void) {\n");
    for (name, fields) in structs {
        // Line: NAME|size|align|field=offset|field=offset...
        let mut fmt = format!("{name}|%zu|%zu");
        let mut args = format!("sizeof({name}), _Alignof({name})");
        for f in fields {
            fmt.push_str(&format!("|{f}=%zu"));
            args.push_str(&format!(", offsetof({name}, {f})"));
        }
        body.push_str(&format!("    printf(\"{fmt}\\n\", {args});\n"));
    }
    body.push_str("    return 0;\n}\n");

    let dir = TempDir::new();
    let src = dir.path.join("probe.c");
    std::fs::write(&src, body).expect("write probe.c");
    let exe = dir.path.join(format!("probe{}", std::env::consts::EXE_SUFFIX));

    let cc = host_c_compiler();
    let compile = Command::new(&cc)
        .arg("-std=c11")
        .arg("-I")
        .arg(header_dir())
        .arg(&src)
        .arg("-o")
        .arg(&exe)
        .output()
        .unwrap_or_else(|e| {
            panic!(
                "the C compiler `{}` (clang) could not be run: {e}. \
                 The offsetof layout proof requires clang (§11); \
                 install LLVM or set $CC.",
                cc.to_string_lossy()
            )
        });
    assert!(
        compile.status.success(),
        "compiling the C offsetof probe failed:\n{}",
        String::from_utf8_lossy(&compile.stderr)
    );

    let run = Command::new(&exe)
        .output()
        .expect("run the compiled C offsetof probe");
    assert!(
        run.status.success(),
        "the C offsetof probe exited with {}:\n{}",
        run.status,
        String::from_utf8_lossy(&run.stderr)
    );
    let stdout = String::from_utf8(run.stdout).expect("probe output is utf-8");

    let mut out = BTreeMap::new();
    for line in stdout.lines().filter(|l| !l.trim().is_empty()) {
        let mut parts = line.split('|');
        let name = parts.next().expect("struct name").to_string();
        let size: u32 = parts.next().expect("size").parse().expect("size number");
        let align: u32 = parts.next().expect("align").parse().expect("align number");
        let mut field_offsets = Vec::new();
        for field in parts {
            let (fname, off) = field.split_once('=').expect("field=offset");
            field_offsets.push((fname.to_string(), off.parse().expect("offset number")));
        }
        out.insert(
            name,
            CLayout {
                size,
                align,
                field_offsets,
            },
        );
    }
    out
}

#[test]
fn language_layout_matches_c_offsetof_for_every_mirrored_struct() {
    let structs = mirrored_structs();

    // Language side: check the mirror and compute its C-ABI layouts.
    let module = check_program(&[SourceFile::new("mirror.ts", MIRROR_SOURCE)])
        .unwrap_or_else(|d| panic!("mirror source did not check clean: {d:?}"));
    let lang: BTreeMap<String, subscript_codegen::StructLayout> = value_class_layouts(&module)
        .expect("value-class layouts")
        .into_iter()
        .map(|s| (s.name.clone(), s))
        .collect();

    // C side: the platform compiler's offsetof/sizeof/_Alignof truth.
    let c = c_truth(&structs);

    let mut report = String::from(
        "\nper-struct layout (language vs C), size/align and field offsets:\n",
    );
    let mut failures: Vec<String> = Vec::new();

    for (name, fields) in &structs {
        let l = lang
            .get(*name)
            .unwrap_or_else(|| panic!("language mirror is missing `{name}`"));
        let cl = c
            .get(*name)
            .unwrap_or_else(|| panic!("C probe is missing `{name}`"));

        report.push_str(&format!(
            "  {name}: lang size={} align={}  |  C size={} align={}\n",
            l.size, l.align, cl.size, cl.align
        ));

        if (l.size, l.align) != (cl.size, cl.align) {
            failures.push(format!(
                "{name}: size/align mismatch — language ({}, {}) vs C ({}, {})",
                l.size, l.align, cl.size, cl.align
            ));
        }

        assert_eq!(
            l.fields.len(),
            fields.len(),
            "{name}: language field count {} != expected {}",
            l.fields.len(),
            fields.len()
        );
        assert_eq!(
            cl.field_offsets.len(),
            fields.len(),
            "{name}: C field count {} != expected {}",
            cl.field_offsets.len(),
            fields.len()
        );

        for (i, fname) in fields.iter().enumerate() {
            let lf = &l.fields[i];
            let (cname, coff) = &cl.field_offsets[i];
            report.push_str(&format!(
                "    .{fname}: lang offset={}  |  C offset={}\n",
                lf.offset, coff
            ));
            if lf.name != *fname || cname != fname {
                failures.push(format!(
                    "{name}: field {i} name mismatch — expected `{fname}`, \
                     language `{}`, C `{cname}`",
                    lf.name
                ));
            }
            if lf.offset != *coff {
                failures.push(format!(
                    "{name}.{fname}: offset mismatch — language {} vs C {coff}",
                    lf.offset
                ));
            }
        }
    }

    // Always surface the numbers so the evidence is visible (`--nocapture`).
    print!("{report}");

    assert!(
        failures.is_empty(),
        "C-ABI layout disagreements (design invariant 1 violated):\n{}\n{report}",
        failures.join("\n")
    );
}
