//! The ship-tier C compile, link, and run support.
//!
//! # Entry program
//!
//! The emitted program has no `main` of its own. It exports
//! `subscript_init` (module-global initializer) and `subscript_export_<name>` for
//! every exported script function. The C entry creates a Context
//! through the runtime's host-driver entry points, calls `subscript_init` and
//! `subscript_export_main`, streams each complete printed line to the process
//! stdout, and reports a trap on stderr with a non-zero exit status. Streaming
//! is required so output already produced survives an aborting native call;
//! the run helper still captures and returns the byte-exact stream.

use std::ffi::OsString;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

use subscript_compiler::{check_program, SourceFile};
use subscript_runtime::TrapKind;

use crate::jit::{AbnormalTermination, RunError, TrapReport};
use crate::lower::internal;
use crate::native::missing_symbol;
use crate::position_table::PositionTable;
use crate::{NativeLibrary, RunConfig, RunOutput};

#[cfg(unix)]
#[path = "../clang_resolver.rs"]
mod clang_resolver;

#[path = "host_source.rs"]
mod host_source;

/// Environment variable naming a prebuilt runtime static library for
/// [`run_c_aot`] to link against. When unset, `run_c_aot` looks for the archive next to the
/// current executable and builds `subscript-runtime` with the
/// workspace's own cargo if it is missing or stale.
///
/// It exists for a host-target link that must use an archive cargo did
/// not just build. Device links pass each cross-compiled archive to the
/// platform C compiler directly.
pub const RUNTIME_STATICLIB_ENV: &str = "SUBSCRIPT_RUNTIME_STATICLIB";

/// The C entry program linked with each ship-tier build.
///
/// It is the single definition used by the host runner and emitted-C files.
/// It is generated output. Do not edit a generated copy.
pub const AOT_ENTRY_C: &str = r#"
#include "program.h"

/* Host entry for a subscript AOT build (compiler.md 8.1).
 * Generated; never hand-edited.
 */
#include <stdio.h>
#include <stddef.h>
#if defined(_WIN32)
#include <io.h>
#include <fcntl.h>
#endif

/* Generated by the C ship tier. */
extern void subscript_kick_async_exports(subscript_rt_context *ctx);

static void call_script_entry(subscript_rt_context *ctx, subscript_main_entry entry) {
    subscript_rt_ctx_enter_script(ctx);
    entry(ctx);
    subscript_rt_ctx_exit_script(ctx);
}

static void write_stdout_line(void *userdata, const uint8_t *line, uint64_t line_len) {
    FILE *stream = (FILE *)userdata;
    if (line_len > 0) {
        fwrite(line, 1, (size_t)line_len, stream);
    }
    fputc('\n', stream);
    fflush(stream);
}

int main(void) {
#if defined(_WIN32)
    /* The sink bytes are compared byte-for-byte against the goldens; the
     * MSVCRT opens stdout in text mode and would translate '\n' to
     * '\r\n'. Binary mode writes the sink through unchanged. No-op on
     * every other platform, which has no text-mode translation. */
    _setmode(_fileno(stdout), _O_BINARY);
#endif
    subscript_rt_context *ctx = subscript_rt_ctx_new();
    if (ctx == NULL) {
        return 2;
    }
    subscript_rt_ctx_set_print_observer(ctx, write_stdout_line, stdout);
    call_script_entry(ctx, subscript_init);
    if (subscript_rt_ctx_trap_kind(ctx) == 0) {
        call_script_entry(ctx, subscript_export_main);
    }
    if (subscript_rt_ctx_trap_kind(ctx) == 0) {
        call_script_entry(ctx, subscript_kick_async_exports);
    }
    while (subscript_rt_ctx_trap_kind(ctx) == 0 &&
           subscript_rt_ctx_async_pending(ctx) != 0) {
        (void)subscript_rt_ctx_async_step(ctx);
    }
    uint64_t len = 0;
    const unsigned char *out = subscript_rt_ctx_stdout(ctx, &len);
    if (len > 0) {
        fwrite(out, 1, (size_t)len, stdout);
    }
    fflush(stdout);
    int status = 0;
    uint32_t kind = subscript_rt_ctx_trap_kind(ctx);
    if (kind != 0) {
        uint64_t mlen = 0;
        const unsigned char *msg = subscript_rt_ctx_trap_message(ctx, &mlen);
        fprintf(stderr, "trap %u %u ", kind, subscript_rt_ctx_trap_pos_id(ctx));
        if (mlen > 0) {
            fwrite(msg, 1, (size_t)mlen, stderr);
        }
        fputc('\n', stderr);
        status = 3;
    }
    subscript_rt_ctx_release(ctx);
    return status;
}
"#;

/// Runtime API without program entry declarations.
pub const HOST_HEADER_C: &str = include_str!("../../runtime/include/subscript_runtime.h");

/// Prefixes a test host body with its generated program header.
/// Supply the `host_header` field from the emitted program.
///
/// The Windows guard keeps stdout in binary mode for byte-exact sink comparisons
/// (compiler.md §11c and §100.2). Other hosts retain their stdout mode.
///
/// # Errors
///
/// Returns an error if the body lacks a C main definition or already spells `_setmode`.
pub fn host_entry(body: &str, program_header: &str) -> Result<String, String> {
    let start =
        host_source::main_body_start(body).ok_or("test host body must define a C main function")?;
    if body.contains("_setmode") {
        return Err("test host body must not spell `_setmode`".into());
    }
    let body = format!(
        "{}\n\
         #ifdef _WIN32\n\
         \x20   (void)_setmode(_fileno(stdout), _O_BINARY);\n\
         #endif\n{}",
        &body[..start],
        &body[start..],
    );
    Ok(format!(
        "{program_header}\n\
         #ifdef _WIN32\n\
         #include <stdio.h>\n\
         #include <fcntl.h>\n\
         #include <io.h>\n\
         #endif\n\
         {body}"
    ))
}

/// A temporary directory removed when the guard is dropped.
struct TempDir {
    path: PathBuf,
}

impl TempDir {
    fn new(tag: &str) -> Result<TempDir, RunError> {
        use std::sync::atomic::{AtomicU64, Ordering};
        static COUNTER: AtomicU64 = AtomicU64::new(0);
        let n = COUNTER.fetch_add(1, Ordering::Relaxed);
        let path = std::env::temp_dir().join(format!(
            "subscript-aot-{}-{}-{}",
            std::process::id(),
            tag,
            n
        ));
        std::fs::create_dir_all(&path)
            .map_err(|e| RunError::Internal(internal(format!("temp dir: {e}"))))?;
        Ok(TempDir { path })
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        // Best effort: a leftover temp directory is not a failure of
        // the run that produced it.
        let _ = std::fs::remove_dir_all(&self.path);
    }
}

/// The directory holding build outputs for the running profile
/// (`.../target/<profile>`), derived from the current executable.
fn build_dir() -> Result<PathBuf, RunError> {
    let exe = std::env::current_exe()
        .map_err(|e| RunError::Internal(internal(format!("current executable: {e}"))))?;
    // Test and example binaries live in `<profile>/deps/`; plain
    // binaries live directly in `<profile>/`.
    let dir = exe
        .parent()
        .ok_or_else(|| RunError::Internal(internal("executable has no directory")))?;
    let dir = if dir.file_name().is_some_and(|n| n == "deps") {
        dir.parent()
            .ok_or_else(|| RunError::Internal(internal("deps directory has no parent")))?
    } else {
        dir
    };
    Ok(dir.to_path_buf())
}

/// Newest modification time under `dir`, recursively. `None` when the
/// tree cannot be read; the caller then treats the archive as stale.
fn newest_mtime(dir: &Path) -> Option<std::time::SystemTime> {
    let mut newest: Option<std::time::SystemTime> = None;
    let mut stack = vec![dir.to_path_buf()];
    while let Some(p) = stack.pop() {
        let meta = std::fs::metadata(&p).ok()?;
        if meta.is_dir() {
            for e in std::fs::read_dir(&p).ok()? {
                stack.push(e.ok()?.path());
            }
        } else if let Ok(t) = meta.modified() {
            newest = Some(newest.map_or(t, |n| n.max(t)));
        }
    }
    newest
}

/// True when `archive` exists and is newer than every runtime source.
fn staticlib_is_fresh(archive: &Path, runtime_dir: &Path) -> bool {
    let Ok(built) = std::fs::metadata(archive).and_then(|m| m.modified()) else {
        return false;
    };
    match newest_mtime(runtime_dir) {
        Some(source) => built >= source,
        None => false,
    }
}

/// Returns the host runtime static-library filename produced by Cargo.
///
/// Windows MSVC uses `subscript_runtime.lib`; every other host uses
/// `libsubscript_runtime.a`.
#[must_use]
pub fn runtime_staticlib_name() -> &'static str {
    if cfg!(all(windows, target_env = "msvc")) {
        "subscript_runtime.lib"
    } else {
        "libsubscript_runtime.a"
    }
}

/// Builds the runtime static library for the running profile and
/// returns its path.
fn build_runtime_staticlib() -> Result<PathBuf, String> {
    let dir = build_dir().map_err(|e| e.to_string())?;
    let archive = dir.join(runtime_staticlib_name());
    let runtime_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../runtime");
    if staticlib_is_fresh(&archive, &runtime_dir) {
        return Ok(archive);
    }
    let profile = dir
        .file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_default();
    let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let mut cmd = Command::new(cargo);
    cmd.arg("build")
        .arg("--offline")
        .arg("--manifest-path")
        .arg(runtime_dir.join("Cargo.toml"));
    if profile == "release" {
        cmd.arg("--release");
    }
    let out = cmd
        .output()
        .map_err(|e| internal(format!("build runtime staticlib: {e}")))?;
    if !out.status.success() {
        return Err(internal(format!(
            "building the runtime static library failed:\n{}",
            String::from_utf8_lossy(&out.stderr)
        )));
    }
    if !archive.is_file() {
        return Err(internal(format!(
            "runtime static library not found at {}; set {RUNTIME_STATICLIB_ENV}",
            archive.display()
        )));
    }
    Ok(archive)
}

/// Locates the runtime static library, building it if necessary.
///
/// The runtime crate declares both `rlib` and `staticlib`; `cargo test`
/// builds only the `rlib` it links against, so the archive is produced
/// on demand with the same cargo and the same profile. Resolution is
/// cached per process and the archive is reused when it is newer than
/// every runtime source, so a test binary that links many programs
/// spawns cargo at most once, and not at all when the archive is
/// already current. Set [`RUNTIME_STATICLIB_ENV`] to bypass all of it.
fn runtime_staticlib() -> Result<PathBuf, RunError> {
    if let Some(p) = std::env::var_os(RUNTIME_STATICLIB_ENV) {
        let path = PathBuf::from(p);
        if !path.is_file() {
            return Err(RunError::Internal(internal(format!(
                "{RUNTIME_STATICLIB_ENV} points at {}, which is not a file",
                path.display()
            ))));
        }
        return Ok(path);
    }
    static RESOLVED: std::sync::OnceLock<Result<PathBuf, String>> = std::sync::OnceLock::new();
    RESOLVED
        .get_or_init(build_runtime_staticlib)
        .clone()
        .map_err(RunError::Internal)
}

/// Path to the runtime static library for the running build profile,
/// building it with the workspace's own cargo when it is missing or
/// older than the runtime sources.
///
/// The ship-tier runner uses it for its link. It is public so that host
/// programs resolve the same archive as the differential gate.
/// [`RUNTIME_STATICLIB_ENV`] overrides it.
///
/// # Errors
///
/// [`RunError::Internal`] when the archive cannot be located or built.
pub fn runtime_staticlib_path() -> Result<PathBuf, RunError> {
    runtime_staticlib()
}

/// Finds `name` on `PATH`, returning its full path when an executable
/// file exists. On Windows the `.exe` extension is tried as well.
#[cfg(all(not(unix), not(all(windows, target_env = "msvc"))))]
fn find_on_path(name: &str) -> Option<PathBuf> {
    let path = std::env::var_os("PATH")?;
    let exts: &[&str] = if cfg!(windows) { &["", ".exe"] } else { &[""] };
    for dir in std::env::split_paths(&path) {
        for ext in exts {
            let cand = dir.join(format!("{name}{ext}"));
            if cand.is_file() {
                return Some(cand);
            }
        }
    }
    None
}

/// Command-line spelling used by a host C compiler.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum CCompilerStyle {
    /// Clang/GCC-compatible command-line spelling.
    Unix,
    /// Microsoft `cl` command-line spelling.
    Msvc,
}

impl CCompilerStyle {
    /// Returns whether this is Microsoft `cl` spelling.
    #[must_use]
    pub fn is_msvc(self) -> bool {
        matches!(self, Self::Msvc)
    }
}

/// The resolved host C compiler for a ship-tier compile/link.
///
/// It carries the program, the environment needed to run it, and the
/// command-line style selected for the host.
#[derive(Debug)]
#[non_exhaustive]
pub struct HostCCompiler {
    program: OsString,
    env: Vec<(OsString, OsString)>,
    style: CCompilerStyle,
}

impl HostCCompiler {
    /// A [`Command`] for the resolved compiler with its toolchain
    /// environment applied. MSVC `cl` cannot find its own headers and
    /// import libraries without the `INCLUDE`/`LIB`/`PATH` the registry
    /// lookup supplies, so that environment travels with the program.
    #[must_use]
    pub fn command(&self) -> Command {
        let mut command = Command::new(&self.program);
        command.envs(self.env.iter().cloned());
        command
    }

    /// Returns the resolved compiler executable.
    #[must_use]
    pub fn program(&self) -> &std::ffi::OsStr {
        &self.program
    }

    /// Returns the compiler's command-line style.
    #[must_use]
    pub fn style(&self) -> CCompilerStyle {
        self.style
    }
}

/// Resolves the platform C compiler used for ship-tier compilation and
/// linking. `$CC` is tried first on Unix. The default is MSVC `cl` with
/// its discovered toolchain environment on windows-msvc (compiler.md
/// §11c). Unix selects a clang that supports x86 `_Float16` (§11/§11b).
///
/// # Errors
///
/// [`RunError::Internal`] when the required host toolchain is unavailable.
/// A missing toolchain is a failure, never a skip (§8.3).
pub fn host_c_compiler() -> Result<HostCCompiler, RunError> {
    #[cfg(not(unix))]
    if let Some(cc) = std::env::var_os("CC") {
        return Ok(HostCCompiler {
            program: cc,
            env: Vec::new(),
            style: if cfg!(all(windows, target_env = "msvc")) {
                CCompilerStyle::Msvc
            } else {
                CCompilerStyle::Unix
            },
        });
    }

    #[cfg(all(windows, target_env = "msvc"))]
    {
        let target = target_lexicon::HOST.to_string();
        let tool = cc::windows_registry::find_tool(&target, "cl.exe").ok_or_else(|| {
            RunError::Internal(internal(format!(
                "MSVC `cl.exe` was not found for target {target}; \
                 install the Visual C++ build tools or set $CC \
                 (compiler.md §11c)"
            )))
        })?;
        Ok(HostCCompiler {
            program: tool.path().as_os_str().to_owned(),
            env: tool.env().to_vec(),
            style: CCompilerStyle::Msvc,
        })
    }

    #[cfg(unix)]
    {
        static RESOLVED: std::sync::OnceLock<Result<PathBuf, String>> = std::sync::OnceLock::new();
        let program = RESOLVED
            .get_or_init(|| {
                clang_resolver::resolve_capable_clang().map_err(|error| error.to_string())
            })
            .clone()
            .map_err(|error| RunError::Internal(internal(error)))?;
        Ok(HostCCompiler {
            program: program.into_os_string(),
            env: Vec::new(),
            style: CCompilerStyle::Unix,
        })
    }

    #[cfg(all(not(unix), not(all(windows, target_env = "msvc"))))]
    {
        let program_files_clang = std::env::var_os("ProgramFiles")
            .map(PathBuf::from)
            .map(|path| path.join("LLVM").join("bin").join("clang.exe"))
            .filter(|path| path.is_file());
        Ok(HostCCompiler {
            program: find_on_path("clang")
                .or(program_files_clang)
                .map(PathBuf::into_os_string)
                .unwrap_or_else(|| "clang".into()),
            env: Vec::new(),
            style: CCompilerStyle::Unix,
        })
    }
}

/// Concatenates a flag `prefix` with a path, as MSVC's `/Fo:` / `/Fe:`
/// output flags require (no separating space between flag and value).
fn prefixed_path_arg(prefix: &str, path: &Path) -> OsString {
    let mut arg = OsString::from(prefix);
    arg.push(path.as_os_str());
    arg
}

/// The MSVC `/Fo:` object-output flag pointing at a directory: a
/// trailing path separator tells `cl` to place each object there under
/// the source basename, which is required when more than one source is
/// compiled in a single invocation.
fn msvc_object_directory_arg(directory: &Path) -> OsString {
    let mut arg = prefixed_path_arg("/Fo:", directory);
    arg.push(std::path::MAIN_SEPARATOR.to_string());
    arg
}

/// Adds the pinned C11 optimization flags for the resolved driver. The
/// emitted ship C targets C11 (compiler.md §11); pinning the dialect
/// keeps the ship tier independent of the platform compiler's default
/// `-std`. On MSVC (§11c) `-fwrapv` is dropped — `cl` wraps signed
/// overflow two's-complement — and `/utf-8` reads the UTF-8 sources
/// without warning C4819. `/fp:strict` replaces `-ffp-contract=off`: it
/// forbids contraction and reassociation as `-ffp-contract=off` does, and
/// additionally stops `cl` from constant-folding an emitted IEEE
/// `1.0 / 0.0` (infinity) at compile time — which `/fp:precise` rejects
/// with error C2124 — deferring it to a runtime infinity instead. It is
/// at least as conservative as `/fp:precise`, so the byte-exact
/// differential is preserved.
///
/// The Unix arm carries the POSIX feature test on Linux (compiler.md §11b).
/// The macro comes from the command line because glibc selects its feature set at the unit's first libc header.
pub fn add_c11_optimized_flags(command: &mut Command, style: CCompilerStyle) {
    if style.is_msvc() {
        command.args(["/nologo", "/std:c11", "/O2", "/utf-8", "/fp:strict"]);
    } else {
        command.args(["-std=c11", "-O2", "-fwrapv", "-ffp-contract=off"]);
        command.args(posix_feature_arguments());
    }
}

/// Adds the AddressSanitizer flags for the resolved driver.
fn add_address_sanitizer_flags(command: &mut Command, style: CCompilerStyle) {
    if style.is_msvc() {
        command.args(["/fsanitize=address", "/Oy-"]);
    } else {
        command.args(["-fsanitize=address", "-fno-omit-frame-pointer"]);
    }
}

/// Renders the output of a failed toolchain command for an error
/// message, with both streams and a label for each.
///
/// MSVC `cl` and `link.exe` write their diagnostics to stdout. Unix
/// compilers write them to stderr. A report of one stream only is
/// therefore empty on one host family, and the failure arrives with no
/// cause (compiler.md §11c.4). An empty stream is normal, so this
/// function drops it and keeps the label of the stream that has content.
#[must_use]
pub fn tool_output_report(output: &std::process::Output) -> String {
    let mut report = String::new();
    for (label, bytes) in [("stdout", &output.stdout), ("stderr", &output.stderr)] {
        let stream = String::from_utf8_lossy(bytes);
        if stream.trim().is_empty() {
            continue;
        }
        report.push_str("--- ");
        report.push_str(label);
        report.push_str(" ---\n");
        report.push_str(&stream);
        if !stream.ends_with('\n') {
            report.push('\n');
        }
    }
    if report.is_empty() {
        report.push_str("(the command printed nothing)\n");
    }
    report
}

/// Adds the executable-output arguments for the resolved driver: MSVC's
/// `/Fe:` naming plus the `-link` linker-arguments marker, or the
/// GNU-style `-o` form.
pub fn add_executable_output(command: &mut Command, executable: &Path, style: CCompilerStyle) {
    if style.is_msvc() {
        command
            .arg(prefixed_path_arg("/Fe:", executable))
            .arg("-link");
    } else {
        command.arg("-o").arg(executable);
    }
}

/// Windows system libraries required when linking the Rust runtime archive.
pub const WINDOWS_SYSTEM_LIBRARIES: &[&str] =
    &["kernel32", "ntdll", "userenv", "ws2_32", "dbghelp"];

const LINUX_SYSTEM_LIBRARIES: &[&str] = &["m", "dl", "pthread", "rt", "util", "gcc_s", "c"];

#[derive(Clone, Copy)]
enum SystemLibraryPlatform {
    Windows,
    Linux,
    MacOs,
    Other,
}

/// Returns the POSIX feature-test arguments for Linux, or no arguments on other hosts.
///
/// The macro comes from the command line (compiler.md §11b).
/// glibc selects its feature set at the unit's first libc header.
#[must_use]
pub fn posix_feature_arguments() -> &'static [&'static str] {
    if cfg!(target_os = "linux") {
        &["-D_POSIX_C_SOURCE=199309L"]
    } else {
        &[]
    }
}

/// Returns the host system-library arguments for `style`.
///
/// Windows uses its five Rust import libraries. Non-macOS Unix uses the
/// native static libraries that `rustc` adds. macOS needs no explicit list.
#[must_use]
pub fn runtime_system_libraries(style: CCompilerStyle) -> Vec<OsString> {
    let platform = if cfg!(target_os = "windows") {
        SystemLibraryPlatform::Windows
    } else if cfg!(target_os = "macos") {
        SystemLibraryPlatform::MacOs
    } else if cfg!(unix) {
        SystemLibraryPlatform::Linux
    } else {
        SystemLibraryPlatform::Other
    };
    system_library_arguments(platform, style)
}

fn system_library_arguments(
    platform: SystemLibraryPlatform,
    style: CCompilerStyle,
) -> Vec<OsString> {
    let libraries = match platform {
        SystemLibraryPlatform::Windows => WINDOWS_SYSTEM_LIBRARIES,
        SystemLibraryPlatform::Linux => LINUX_SYSTEM_LIBRARIES,
        SystemLibraryPlatform::MacOs | SystemLibraryPlatform::Other => return Vec::new(),
    };
    libraries
        .iter()
        .map(|name| {
            if matches!(platform, SystemLibraryPlatform::Windows) && style.is_msvc() {
                OsString::from(format!("{name}.lib"))
            } else {
                OsString::from(format!("-l{name}"))
            }
        })
        .collect()
}

/// Returns one joined include-directory argument in the selected spelling.
#[must_use]
pub fn include_directory_arg(style: CCompilerStyle, directory: &Path) -> OsString {
    let prefix = if style.is_msvc() { "/I" } else { "-I" };
    prefixed_path_arg(prefix, directory)
}

/// Directs compiler-created object files into `directory` when required.
///
/// This adds MSVC's joined `/Fo:<dir>\` argument and is a no-op for a
/// Unix-style compiler, which writes no intermediate object in a one-shot
/// compile-and-link command.
pub fn add_object_directory(command: &mut Command, directory: &Path, style: CCompilerStyle) {
    if style.is_msvc() {
        command.arg(msvc_object_directory_arg(directory));
    }
}

fn require_native_symbols(
    required: &[String],
    libraries: &[NativeLibrary],
) -> Result<(), RunError> {
    match missing_symbol(required, libraries) {
        Some(name) => Err(RunError::UnresolvedForeignSymbol(name.to_string())),
        None => Ok(()),
    }
}

fn add_native_include_directories(
    command: &mut Command,
    libraries: &[NativeLibrary],
    style: CCompilerStyle,
) {
    for library in libraries {
        for directory in library.include_directories() {
            command.arg(include_directory_arg(style, directory));
        }
    }
}

/// Adds the caller's link inputs after the emitted translation units (compiler.md §54).
fn add_native_link_inputs(command: &mut Command, libraries: &[NativeLibrary]) {
    for library in libraries {
        for source in library.c_sources() {
            command.arg(source);
        }
    }
}

/// Writes `bytes` to `path`.
fn write_file(path: &Path, bytes: &[u8]) -> Result<(), RunError> {
    let mut f = std::fs::File::create(path)
        .map_err(|e| RunError::Internal(internal(format!("create {}: {e}", path.display()))))?;
    f.write_all(bytes)
        .map_err(|e| RunError::Internal(internal(format!("write {}: {e}", path.display()))))
}

/// Compiles, links, and runs `files` through the **ship tier** (§11) on
/// the host target, returning the exact stdout bytes the program
/// produced.
///
/// The ship tier emits C ([`crate::emit_c`]), which the platform C
/// compiler compiles at `-O2 -ffp-contract=off` and links with the
/// runtime static library and host entry [`AOT_ENTRY_C`]. The emitted C
/// exports `subscript_init` and `subscript_export_main`.
/// The whole cycle happens in a temporary directory removed before
/// returning. The C compiler's absence is a failure, never a skip (the
/// gate machine is the development machine, §8.3).
///
/// # Errors
///
/// [`RunError::Rejected`] when the checker rejects the program,
/// [`RunError::Trap`] when the linked program trapped (mapped back
/// through the emitted position table, with pre-trap stdout),
/// [`RunError::UnresolvedForeignSymbol`] when the program calls a symbol
/// but no native library was supplied, [`RunError::AbnormalTermination`]
/// when the linked program ends outside the trap protocol, and
/// [`RunError::Internal`] on emission, toolchain, compile, link, or
/// execution failures.
pub fn run_c_aot(files: &[SourceFile]) -> Result<Vec<u8>, RunError> {
    Ok(run_c_aot_configured(files, RunConfig::default())?.stdout)
}

/// Runs the shipping tier with one complete option record.
///
/// # Errors
///
/// Returns the same [`RunError`] variants as [`run_c_aot`]. A request for
/// development-tier memory accounting produces [`RunError::Internal`].
pub fn run_c_aot_configured(
    files: &[SourceFile],
    config: RunConfig<'_>,
) -> Result<RunOutput, RunError> {
    if config.memory_accounting {
        return Err(RunError::Internal(internal(
            "Context memory accounting is not available in the shipping tier",
        )));
    }
    let stdout = execute_c_aot(files, config)?;
    Ok(RunOutput {
        stdout,
        memory_accounting: None,
    })
}

/// Compiles, links, and runs `files` through the emitted-C ship tier with
/// caller-supplied native libraries.
///
/// # Errors
///
/// Returns the same [`RunError`] variants as [`run_c_aot`], including
/// [`RunError::UnresolvedForeignSymbol`] when a called foreign symbol is
/// absent from `libraries`.
pub fn run_c_aot_with_native_libraries(
    files: &[SourceFile],
    libraries: &[NativeLibrary],
) -> Result<Vec<u8>, RunError> {
    Ok(run_c_aot_configured(
        files,
        RunConfig {
            native_libraries: libraries,
            ..RunConfig::default()
        },
    )?
    .stdout)
}

/// Compiles, links, and runs `files` through the emitted-C ship tier with
/// caller-supplied native libraries and optional host lifecycle hooks.
///
/// `pre_entry_hook`, when present, names a C function called after
/// `subscript_init` and before the exported script entry. `post_run_hook`,
/// when present, names a C function called after the async pump and before
/// the Context is released. Each hook has the C signature
/// `void hook(subscript_rt_context *)`; hook names must be C identifiers.
/// Neither hook is entered as script code. Both calls are unconditional:
/// the pre-entry hook runs even when initialization has trapped, and the
/// post-run hook runs regardless of the Context's trap state.
/// The generated entry declares and calls only the hooks supplied here, so
/// no weak-symbol or link-time discovery mechanism is involved.
///
/// # Errors
///
/// Returns the same [`RunError`] variants as
/// [`run_c_aot_with_native_libraries`]. [`RunError::Internal`] is returned
/// when a supplied hook name is not a C identifier.
pub fn run_c_aot_with_native_libraries_and_host_hooks(
    files: &[SourceFile],
    libraries: &[NativeLibrary],
    pre_entry_hook: Option<&str>,
    post_run_hook: Option<&str>,
) -> Result<Vec<u8>, RunError> {
    Ok(run_c_aot_configured(
        files,
        RunConfig {
            native_libraries: libraries,
            pre_entry_hook,
            post_run_hook,
            ..RunConfig::default()
        },
    )?
    .stdout)
}

/// Runs the emitted-C ship tier with freed-handle diagnostics enabled and
/// the caller-supplied native libraries.
///
/// The host establishes threshold 0 and the recommended 1 GiB retention
/// budget before `subscript_init`, so retained-dead diagnostics have the
/// same coverage as the dev-JIT diagnostic runner.
///
/// # Errors
///
/// Returns the same [`RunError`] variants as
/// [`run_c_aot_with_native_libraries`].
pub fn run_c_aot_with_freed_handle_diagnostics_and_native_libraries(
    files: &[SourceFile],
    libraries: &[NativeLibrary],
) -> Result<Vec<u8>, RunError> {
    Ok(run_c_aot_configured(
        files,
        RunConfig {
            native_libraries: libraries,
            freed_handle_diagnostics: true,
            ..RunConfig::default()
        },
    )?
    .stdout)
}

/// Runs the emitted-C ship tier while refusing the `n`-th object-level
/// Context allocation after Context creation.
///
/// The injected fault is armed before `subscript_init`, so module-initializer
/// allocations are part of the count. When
/// `SUBSCRIPT_C_AOT_ASAN` is set, the generated C and host entry are
/// compiled and linked with AddressSanitizer.
///
/// # Errors
///
/// Returns the same [`RunError`] variants as [`run_c_aot`].
pub fn run_c_aot_with_alloc_failure(files: &[SourceFile], n: u64) -> Result<Vec<u8>, RunError> {
    Ok(run_c_aot_configured(
        files,
        RunConfig {
            fail_alloc_after: Some(n),
            ..RunConfig::default()
        },
    )?
    .stdout)
}

fn validate_host_hook_name(name: &str) -> Result<(), RunError> {
    let mut bytes = name.bytes();
    let valid_start = bytes
        .next()
        .is_some_and(|byte| byte == b'_' || byte.is_ascii_alphabetic());
    if !valid_start || !bytes.all(|byte| byte == b'_' || byte.is_ascii_alphanumeric()) {
        return Err(RunError::Internal(internal(format!(
            "host hook name `{name}` is not a C identifier"
        ))));
    }
    Ok(())
}

fn aot_entry_with_host_hooks(
    pre_entry_hook: Option<&str>,
    post_run_hook: Option<&str>,
) -> Result<String, RunError> {
    for hook in [pre_entry_hook, post_run_hook].into_iter().flatten() {
        validate_host_hook_name(hook)?;
    }
    if pre_entry_hook.is_none() && post_run_hook.is_none() {
        return Ok(AOT_ENTRY_C.to_string());
    }

    const DECLARATION_ANCHOR: &str =
        "extern void subscript_kick_async_exports(subscript_rt_context *ctx);";
    const PRE_ENTRY_ANCHOR: &str = "    call_script_entry(ctx, subscript_init);";
    const POST_RUN_ANCHOR: &str = "    uint64_t len = 0;";
    for anchor in [DECLARATION_ANCHOR, PRE_ENTRY_ANCHOR, POST_RUN_ANCHOR] {
        if !AOT_ENTRY_C.contains(anchor) {
            return Err(RunError::Internal(internal(
                "AOT entry host-hook anchor moved",
            )));
        }
    }

    let mut declarations = String::new();
    if let Some(hook) = pre_entry_hook {
        declarations.push_str(&format!("\nextern void {hook}(subscript_rt_context *ctx);"));
    }
    if let Some(hook) = post_run_hook.filter(|hook| Some(*hook) != pre_entry_hook) {
        declarations.push_str(&format!("\nextern void {hook}(subscript_rt_context *ctx);"));
    }

    let mut entry = AOT_ENTRY_C.replacen(
        DECLARATION_ANCHOR,
        &format!("{DECLARATION_ANCHOR}{declarations}"),
        1,
    );
    if let Some(hook) = pre_entry_hook {
        entry = entry.replacen(
            PRE_ENTRY_ANCHOR,
            &format!("{PRE_ENTRY_ANCHOR}\n    {hook}(ctx);"),
            1,
        );
    }
    if let Some(hook) = post_run_hook {
        entry = entry.replacen(
            POST_RUN_ANCHOR,
            &format!("    {hook}(ctx);\n{POST_RUN_ANCHOR}"),
            1,
        );
    }
    Ok(entry)
}

/// One linked ship-tier program, with the temporary directory that owns
/// its files and the position table its traps resolve through.
struct LinkedProgram {
    directory: TempDir,
    executable: PathBuf,
    positions: PositionTable,
}

fn execute_c_aot(files: &[SourceFile], config: RunConfig<'_>) -> Result<Vec<u8>, RunError> {
    let program = build_c_aot(files, config)?;
    let run = Command::new(&program.executable)
        .output()
        .map_err(|e| RunError::Internal(internal(format!("run linked program: {e}"))))?;
    drop(program.directory);
    if run.status.success() {
        return Ok(run.stdout);
    }
    match parse_trap(&run.stderr, &program.positions, &run.stdout) {
        Some(report) => Err(RunError::Trap(report)),
        None => Err(RunError::AbnormalTermination(AbnormalTermination {
            status: format!("linked C program exited with {}", run.status),
            stdout: run.stdout,
            stderr: run.stderr,
        })),
    }
}

fn build_c_aot(files: &[SourceFile], config: RunConfig<'_>) -> Result<LinkedProgram, RunError> {
    let RunConfig {
        native_libraries: libraries,
        fail_alloc_after,
        freed_handle_diagnostics,
        pre_entry_hook,
        post_run_hook,
        ..
    } = config;
    let hir = check_program(files).map_err(RunError::Rejected)?;
    let program = crate::emit_c(&hir).map_err(|error| RunError::Internal(internal(error)))?;
    require_native_symbols(&program.foreign_symbols, libraries)?;
    let staticlib = runtime_staticlib()?;
    let dir = TempDir::new("crun")?;

    let src_path = dir.path.join("program.c");
    let entry_path = dir.path.join("entry.c");
    let exe_path = dir
        .path
        .join(format!("program{}", std::env::consts::EXE_SUFFIX));
    write_file(&src_path, program.source.as_bytes())?;
    write_file(&dir.path.join("program.h"), program.host_header.as_bytes())?;
    let anchor = "    call_script_entry(ctx, subscript_init);";
    let mut entry = aot_entry_with_host_hooks(pre_entry_hook, post_run_hook)?;
    if !entry.contains(anchor) {
        return Err(RunError::Internal(internal(
            "AOT entry Context-configuration anchor moved",
        )));
    }
    let mut setup = String::new();
    if freed_handle_diagnostics {
        setup.push_str(concat!(
            "    if (subscript_rt_ctx_set_freed_handle_diagnostics(\n",
            "            ctx, 1u, 0u,\n",
            "            SUBSCRIPT_RT_FREED_HANDLE_DIAGNOSTICS_DEFAULT_MAX_RETAINED_BYTES) == 0) {\n",
            "        subscript_rt_ctx_release(ctx);\n",
            "        return 2;\n",
            "    }\n",
        ));
    }
    if let Some(n) = fail_alloc_after {
        setup.push_str(&format!(
            "    subscript_rt_ctx_fail_alloc_after(ctx, {n}u);\n"
        ));
    }
    if !setup.is_empty() {
        setup.push_str(anchor);
        entry = entry.replacen(anchor, &setup, 1);
    }
    write_file(&entry_path, entry.as_bytes())?;

    let cc = host_c_compiler()?;
    let address_sanitizer = std::env::var_os("SUBSCRIPT_C_AOT_ASAN").is_some();
    let mut command = cc.command();
    // The emitted ship C targets C11 (compiler block §11); the language's
    // C-ABI layout, compound literals, `_Alignof`, and
    // `<stdbool.h>`/`<stdint.h>` types are all C11. Pinning the dialect
    // keeps the ship tier independent of the platform compiler's default
    // `-std`. Signed overflow must wrap two's-complement (the language's
    // semantics); `-fwrapv` establishes that off MSVC, `cl` wraps by
    // default (§11c).
    add_c11_optimized_flags(&mut command, cc.style());
    if address_sanitizer {
        add_address_sanitizer_flags(&mut command, cc.style());
    }
    if cc.style().is_msvc() {
        // Two sources (the program and the entry) plus any native
        // sources are compiled in one invocation; direct their objects
        // into the temp dir under their basenames.
        add_object_directory(&mut command, &dir.path, cc.style());
    }
    command.arg(include_directory_arg(cc.style(), &dir.path));
    add_native_include_directories(&mut command, libraries, cc.style());
    command.arg(&src_path).arg(&entry_path);
    add_native_link_inputs(&mut command, libraries);
    command
        .arg(&staticlib)
        .args(runtime_system_libraries(cc.style()));
    add_executable_output(&mut command, &exe_path, cc.style());
    let compile = command.output().map_err(|e| {
        RunError::Internal(internal(format!(
            "the platform C compiler `{}` could not be run: {e}; \
                 install the host C toolchain or set $CC (compiler.md §11c)",
            cc.program.to_string_lossy()
        )))
    })?;
    if !compile.status.success() {
        return Err(RunError::Internal(internal(format!(
            "compiling/linking the emitted C failed:\n{}",
            tool_output_report(&compile)
        ))));
    }

    Ok(LinkedProgram {
        directory: dir,
        executable: exe_path,
        positions: program.positions,
    })
}

/// Parses the entry program's `trap <kind> <pos_id> <message>` line
/// back into a report, resolving the position through the emitted C
/// position table.
fn parse_trap(stderr: &[u8], positions: &PositionTable, stdout: &[u8]) -> Option<TrapReport> {
    let text = std::str::from_utf8(stderr).ok()?;
    let line = text.lines().find(|l| l.starts_with("trap "))?;
    let mut parts = line.splitn(4, ' ');
    parts.next()?;
    let kind = TrapKind::from_u32(parts.next()?.parse().ok()?)?;
    let pos_id: u32 = parts.next()?.parse().ok()?;
    let message = parts.next().unwrap_or("").to_string();
    Some(TrapReport {
        rule: kind,
        message,
        // §112 rule 1: the recorded id resolves through the emitted
        // table, and id 0 is its reserved entry, so both tiers report
        // the same position.
        pos: positions.report_position(pos_id),
        stdout: stdout.to_vec(),
    })
}

#[cfg(test)]
#[path = "ship_tests.rs"]
mod tests;
