//! Named subset rejection sites and their accepted TypeScript classes.

use super::Checker;
use crate::ambient::ApiRejection;
use crate::diag::{Pos, RuleCode};
use crate::divergence::Divergence;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum RejectionSite {
    Api(ApiRejection),
    MirrorParameter,
    ArraySpreadFixedArray,
    ArraySpreadMap,
    ArraySpreadGenerator,
    ArraySpreadSource,
    MapCopyKey,
    ContextBytesMissingType,
    ContextBytesTypeCount,
    ContextBytesArgumentCount,
    ContextBytesSpread,
    CallSpread,
    SetSourceSpread,
    SetSourceDomain,
    NewMapSetKey,
    RegexSticky,
    ContextValue,
    NumberValue,
    JsonValue,
    DateValue,
    MapSetValue,
    NumberGlobalValue,
    CoercingGlobalValue,
    RegexMember,
    DateMemberWrite,
    DateMethodValue,
    NumberMethodValue,
    NumberMethodArgumentCount,
    ArrayElementDomain,
    ArrayJoinDomain,
    ArrayCallbackSpread,
    ArrayAccumulatorDomain,
    ArrayMapResult,
    MapGroupByKey,
    ArrayStaticMember,
    ArrayFromTypeCount,
    ArrayFromArgumentCount,
    ArrayFromSpread,
    ArrayFromSource,
    CallbackParameterCount,
    ContextMember,
    JsonMember,
    ArrayFromValue,
    ArrayMember,
    MapGroupByValue,
    MapSetMember,
    MathMemberWrite,
    MathMethodValue,
    MathMember,
    MathCallCount,
    NumberMemberWrite,
    NumberStaticValue,
    NumberMember,
    NumberPredicateCount,
    NumberGlobalCount,
    RegexExec,
    StringPatternSpread,
    StringSearchPattern,
    DateStaticWrite,
    DateStaticValue,
    DateNewSpread,
    DateMember,
    Float16Unary,
    JsonStaticMember,
    JsonStringifyCount,
    JsonStringifySpread,
    JsonStringifyDomain,
    JsonStringifyHelper,
    JsonParseCount,
    JsonParseSpread,
    JsonParseTypeCount,
    JsonParseTarget,
    JsonParseDomain,
    JsonParseHelper,
    JsonError,
    ForOfEntries,
    ForOfKeys,
    ForOfMap,
    ForOfUserClass,
    ForOfSubject,
    RegexMatchType,
    MapSetTypeKey,
    Float16Update,
    Float16Binary,
}

impl RejectionSite {
    pub(super) fn divergence(self) -> Option<Divergence> {
        match self {
            Self::Api(row) => row.divergence,
            Self::MirrorParameter => Some(Divergence::MirrorParameterPattern),
            Self::ArraySpreadFixedArray => Some(Divergence::FixedArraySpread),
            Self::ArraySpreadMap => Some(Divergence::BareMapToArray),
            Self::ArraySpreadGenerator => Some(Divergence::GeneratorSingleUse),
            Self::ArraySpreadSource => None,
            Self::MapCopyKey => Some(Divergence::MapKeyKind),
            Self::ContextBytesMissingType => Some(Divergence::ExplicitIntrinsicTypeArguments),
            Self::ContextBytesTypeCount => None,
            Self::ContextBytesArgumentCount => None,
            Self::ContextBytesSpread => Some(Divergence::VariadicArguments),
            Self::CallSpread => Some(Divergence::VariadicArguments),
            Self::SetSourceSpread => Some(Divergence::VariadicArguments),
            Self::SetSourceDomain => Some(Divergence::SourceConstructionDomain),
            Self::NewMapSetKey => Some(Divergence::MapKeyKind),
            Self::RegexSticky => Some(Divergence::RegExpSubset),
            Self::ContextValue => Some(Divergence::CompilerOwnedValue),
            Self::NumberValue => Some(Divergence::CompilerOwnedValue),
            Self::JsonValue => Some(Divergence::CompilerOwnedValue),
            Self::DateValue => Some(Divergence::CompilerOwnedValue),
            Self::MapSetValue => Some(Divergence::CompilerOwnedValue),
            Self::NumberGlobalValue => Some(Divergence::CompilerOwnedValue),
            Self::CoercingGlobalValue => Some(Divergence::NumberCoercionAndArguments),
            Self::RegexMember => Some(Divergence::RegExpSubset),
            Self::DateMemberWrite => Some(Divergence::DateSubset),
            Self::DateMethodValue => Some(Divergence::CompilerOwnedValue),
            Self::NumberMethodValue => Some(Divergence::CompilerOwnedValue),
            Self::NumberMethodArgumentCount => None,
            Self::ArrayElementDomain => Some(Divergence::MethodTypeDomain),
            Self::ArrayJoinDomain => Some(Divergence::ArrayJoinDomain),
            Self::ArrayCallbackSpread => Some(Divergence::VariadicArguments),
            Self::ArrayAccumulatorDomain => Some(Divergence::MethodTypeDomain),
            Self::ArrayMapResult => Some(Divergence::MethodTypeDomain),
            Self::MapGroupByKey => Some(Divergence::MapKeyKind),
            Self::ArrayStaticMember => Some(Divergence::NamespaceObjectMember),
            Self::ArrayFromTypeCount => Some(Divergence::ExplicitIntrinsicTypeArguments),
            Self::ArrayFromArgumentCount => None,
            Self::ArrayFromSpread => Some(Divergence::VariadicArguments),
            Self::ArrayFromSource => Some(Divergence::SourceConstructionDomain),
            Self::CallbackParameterCount => Some(Divergence::CallbackParameterShape),
            Self::ContextMember => Some(Divergence::CompilerOwnedValue),
            Self::JsonMember => Some(Divergence::CompilerOwnedValue),
            Self::ArrayFromValue => Some(Divergence::CompilerOwnedValue),
            Self::ArrayMember => Some(Divergence::NamespaceObjectMember),
            Self::MapGroupByValue => Some(Divergence::CompilerOwnedValue),
            Self::MapSetMember => Some(Divergence::NamespaceObjectMember),
            Self::MathMemberWrite => Some(Divergence::MathSubset),
            Self::MathMethodValue => Some(Divergence::MathSubset),
            Self::MathMember => Some(Divergence::MathSubset),
            Self::MathCallCount => Some(Divergence::MathSubset),
            Self::NumberMemberWrite => Some(Divergence::CompilerOwnedValue),
            Self::NumberStaticValue => Some(Divergence::CompilerOwnedValue),
            Self::NumberMember => Some(Divergence::NamespaceObjectMember),
            Self::NumberPredicateCount => None,
            Self::NumberGlobalCount => None,
            Self::RegexExec => Some(Divergence::RegExpSubset),
            Self::StringPatternSpread => Some(Divergence::VariadicArguments),
            Self::StringSearchPattern => Some(Divergence::StringSearchPattern),
            Self::DateStaticWrite => Some(Divergence::CompilerOwnedValue),
            Self::DateStaticValue => Some(Divergence::CompilerOwnedValue),
            Self::DateNewSpread => Some(Divergence::VariadicArguments),
            Self::DateMember => Some(Divergence::DateSubset),
            Self::Float16Unary => Some(Divergence::StorageOnlyFloat16),
            Self::JsonStaticMember => Some(Divergence::NamespaceObjectMember),
            Self::JsonStringifyCount => Some(Divergence::JsonCallArguments),
            Self::JsonStringifySpread => Some(Divergence::VariadicArguments),
            Self::JsonStringifyDomain => Some(Divergence::JsonTypeDomain),
            Self::JsonStringifyHelper => None,
            Self::JsonParseCount => None,
            Self::JsonParseSpread => Some(Divergence::VariadicArguments),
            Self::JsonParseTypeCount => None,
            Self::JsonParseTarget => Some(Divergence::JsonSubset),
            Self::JsonParseDomain => Some(Divergence::JsonTypeDomain),
            Self::JsonParseHelper => None,
            Self::JsonError => Some(Divergence::JsonSubset),
            Self::ForOfEntries => Some(Divergence::NoTupleType),
            Self::ForOfKeys => None,
            Self::ForOfMap => Some(Divergence::BareMapSubject),
            Self::ForOfUserClass => None,
            Self::ForOfSubject => None,
            Self::RegexMatchType => Some(Divergence::RegExpSubset),
            Self::MapSetTypeKey => Some(Divergence::MapKeyKind),
            Self::Float16Update => Some(Divergence::StorageOnlyFloat16),
            Self::Float16Binary => Some(Divergence::StorageOnlyFloat16),
        }
    }
}

impl Checker<'_> {
    pub(super) fn reject_subset(
        &mut self,
        site: RejectionSite,
        message: impl Into<String>,
        pos: Pos,
    ) {
        let message = message.into();
        #[cfg(test)]
        super::rejection_total::record_site(site, &message, &pos);
        let code = if site == RejectionSite::MirrorParameter {
            RuleCode::S100
        } else {
            RuleCode::S014
        };
        if let Some(divergence) = site.divergence() {
            self.error_diverging(code, message, pos, divergence);
        } else {
            self.error(code, message, pos);
        }
    }
}
