//! Named subset rejection sites and their accepted TypeScript classes.

use super::Checker;
use crate::ambient::ApiRejection;
use crate::diag::{Diagnostic, Pos, RuleCode};
use crate::divergence::Divergence;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum RejectionSite {
    Api(ApiRejection),
    MirrorParameter,
    ArraySpreadFixedArray,
    ArraySpreadMap,
    ArraySpreadGenerator,
    ArraySpreadSource,
    MapCopyKey,
    ContextBytesMissingType,
    ContextBytesTypeCount,
    ContextBytesArgumentCount,
    ContextBytesSpread,
    CallSpread,
    SetSourceSpread,
    SetSourceDomain,
    NewMapSetKey,
    RegexSticky,
    ContextValue,
    NumberValue,
    JsonValue,
    DateValue,
    MapSetValue,
    NumberGlobalValue,
    CoercingGlobalValue,
    RegexMember,
    DateMemberWrite,
    DateMethodValue,
    NumberMethodValue,
    NumberMethodArgumentCount,
    ArrayElementDomain,
    ArrayJoinDomain,
    ArrayCallbackSpread,
    ArrayAccumulatorDomain,
    ArrayMapResult,
    MapGroupByKey,
    ArrayStaticMember,
    ArrayFromTypeCount,
    ArrayFromArgumentCount,
    ArrayFromSpread,
    ArrayFromSource,
    CallbackParameterCount,
    ContextMember,
    JsonMember,
    ArrayFromValue,
    ArrayMember,
    MapGroupByValue,
    MapSetMember,
    MathMemberWrite,
    MathMethodValue,
    MathMember,
    MathCallCount,
    NumberMemberWrite,
    NumberStaticValue,
    NumberMember,
    NumberPredicateCount,
    NumberGlobalCount,
    RegexExec,
    StringPatternSpread,
    StringSearchPattern,
    DateStaticWrite,
    DateStaticValue,
    DateNewSpread,
    DateMember,
    Float16Unary,
    JsonStaticMember,
    JsonStringifyCount,
    JsonStringifySpread,
    JsonStringifyDomain,
    JsonStringifyHelper,
    JsonParseCount,
    JsonParseSpread,
    JsonParseTypeCount,
    JsonParseTarget,
    JsonParseDomain,
    JsonParseHelper,
    JsonError,
    ForOfEntries,
    ForOfKeys,
    ForOfMap,
    ForOfUserClass,
    ForOfSubject,
    RegexMatchType,
    MapSetTypeKey,
    Float16Update,
    Float16Binary,
}

impl RejectionSite {
    pub(super) fn divergence(self) -> Divergence {
        match self {
            Self::Api(row) => row.divergence,
            Self::MirrorParameter => Divergence::MirrorParameterPattern,
            Self::ArraySpreadFixedArray => Divergence::FixedArraySpread,
            Self::ArraySpreadMap => Divergence::BareMapToArray,
            Self::ArraySpreadGenerator => Divergence::GeneratorSingleUse,
            Self::ArraySpreadSource => Divergence::UserIterationProtocol,
            Self::MapCopyKey => Divergence::MapKeyKind,
            Self::ContextBytesMissingType => Divergence::ExplicitIntrinsicTypeArguments,
            Self::ContextBytesTypeCount => Divergence::ExplicitIntrinsicTypeArguments,
            Self::ContextBytesArgumentCount => Divergence::ContextCallArguments,
            Self::ContextBytesSpread => Divergence::VariadicArguments,
            Self::CallSpread => Divergence::VariadicArguments,
            Self::SetSourceSpread => Divergence::VariadicArguments,
            Self::SetSourceDomain => Divergence::SourceConstructionDomain,
            Self::NewMapSetKey => Divergence::MapKeyKind,
            Self::RegexSticky => Divergence::RegExpSubset,
            Self::ContextValue => Divergence::CompilerOwnedValue,
            Self::NumberValue => Divergence::CompilerOwnedValue,
            Self::JsonValue => Divergence::CompilerOwnedValue,
            Self::DateValue => Divergence::CompilerOwnedValue,
            Self::MapSetValue => Divergence::CompilerOwnedValue,
            Self::NumberGlobalValue => Divergence::CompilerOwnedValue,
            Self::CoercingGlobalValue => Divergence::NumberCoercionAndArguments,
            Self::RegexMember => Divergence::RegExpSubset,
            Self::DateMemberWrite => Divergence::DateSubset,
            Self::DateMethodValue => Divergence::CompilerOwnedValue,
            Self::NumberMethodValue => Divergence::CompilerOwnedValue,
            Self::NumberMethodArgumentCount => Divergence::NumberFormattingArguments,
            Self::ArrayElementDomain => Divergence::MethodTypeDomain,
            Self::ArrayJoinDomain => Divergence::ArrayJoinDomain,
            Self::ArrayCallbackSpread => Divergence::VariadicArguments,
            Self::ArrayAccumulatorDomain => Divergence::MethodTypeDomain,
            Self::ArrayMapResult => Divergence::MethodTypeDomain,
            Self::MapGroupByKey => Divergence::MapKeyKind,
            Self::ArrayStaticMember => Divergence::NamespaceObjectMember,
            Self::ArrayFromTypeCount => Divergence::ExplicitIntrinsicTypeArguments,
            Self::ArrayFromArgumentCount => Divergence::ArraySourceArguments,
            Self::ArrayFromSpread => Divergence::VariadicArguments,
            Self::ArrayFromSource => Divergence::SourceConstructionDomain,
            Self::CallbackParameterCount => Divergence::CallbackParameterShape,
            Self::ContextMember => Divergence::CompilerOwnedValue,
            Self::JsonMember => Divergence::CompilerOwnedValue,
            Self::ArrayFromValue => Divergence::CompilerOwnedValue,
            Self::ArrayMember => Divergence::NamespaceObjectMember,
            Self::MapGroupByValue => Divergence::CompilerOwnedValue,
            Self::MapSetMember => Divergence::NamespaceObjectMember,
            Self::MathMemberWrite => Divergence::MathSubset,
            Self::MathMethodValue => Divergence::MathSubset,
            Self::MathMember => Divergence::MathSubset,
            Self::MathCallCount => Divergence::MathSubset,
            Self::NumberMemberWrite => Divergence::CompilerOwnedValue,
            Self::NumberStaticValue => Divergence::CompilerOwnedValue,
            Self::NumberMember => Divergence::NamespaceObjectMember,
            Self::NumberPredicateCount => Divergence::NumberPredicateArguments,
            Self::NumberGlobalCount => Divergence::NumberCoercionAndArguments,
            Self::RegexExec => Divergence::RegExpSubset,
            Self::StringPatternSpread => Divergence::VariadicArguments,
            Self::StringSearchPattern => Divergence::StringSearchPattern,
            Self::DateStaticWrite => Divergence::CompilerOwnedValue,
            Self::DateStaticValue => Divergence::CompilerOwnedValue,
            Self::DateNewSpread => Divergence::VariadicArguments,
            Self::DateMember => Divergence::DateSubset,
            Self::Float16Unary => Divergence::StorageOnlyFloat16,
            Self::JsonStaticMember => Divergence::NamespaceObjectMember,
            Self::JsonStringifyCount => Divergence::JsonCallArguments,
            Self::JsonStringifySpread => Divergence::VariadicArguments,
            Self::JsonStringifyDomain => Divergence::JsonTypeDomain,
            Self::JsonStringifyHelper => Divergence::JsonTypeDomain,
            Self::JsonParseCount => Divergence::JsonCallArguments,
            Self::JsonParseSpread => Divergence::VariadicArguments,
            Self::JsonParseTypeCount => Divergence::JsonTypeArguments,
            Self::JsonParseTarget => Divergence::JsonSubset,
            Self::JsonParseDomain => Divergence::JsonTypeDomain,
            Self::JsonParseHelper => Divergence::JsonTypeDomain,
            Self::JsonError => Divergence::JsonSubset,
            Self::ForOfEntries => Divergence::NoTupleType,
            Self::ForOfKeys => Divergence::FusedViewDomain,
            Self::ForOfMap => Divergence::BareMapSubject,
            Self::ForOfUserClass => Divergence::UserIterationProtocol,
            Self::ForOfSubject => Divergence::IterationSubjectDomain,
            Self::RegexMatchType => Divergence::RegExpSubset,
            Self::MapSetTypeKey => Divergence::MapKeyKind,
            Self::Float16Update => Divergence::StorageOnlyFloat16,
            Self::Float16Binary => Divergence::StorageOnlyFloat16,
        }
    }
}

impl Checker<'_> {
    pub(super) fn reject_subset(
        &mut self,
        site: RejectionSite,
        message: impl Into<String>,
        pos: Pos,
    ) {
        let message = message.into();
        #[cfg(test)]
        super::rejection_total::record_site(site, &message, &pos);
        let code = if site == RejectionSite::MirrorParameter {
            RuleCode::S100
        } else {
            RuleCode::S014
        };
        let mut diagnostic = Diagnostic::new(code, message, pos);
        diagnostic.divergence = Some(site.divergence());
        self.diags.push(diagnostic);
    }
}
