/* Read roots of compiler.md §187 rule 3: each struct crosses as the
 * code-generation fact passes it. The tests bind subsets of this header. */
#ifndef SUBSCRIPT_READ_ROOT_H
#define SUBSCRIPT_READ_ROOT_H

#include <stdint.h>
#include <stddef.h>

typedef struct RrView { const char *data; size_t len; } RrView;
typedef struct RrDevice_ *RrDevice;
typedef struct RrPoint { int32_t x; } RrPoint;
typedef struct RrQ { int32_t y; } RrQ;
typedef struct RrHolder { int32_t k; RrPoint *p; } RrHolder;
typedef struct RrInner { int32_t x; RrQ *q; } RrInner;
typedef struct RrOuter { int32_t k; RrInner *inner; } RrOuter;
typedef struct RrOuterConst { int32_t k; const RrInner *inner; } RrOuterConst;
typedef struct RrNamed { RrView name; void *ud; } RrNamed;
typedef struct RrDeviceNamed { RrView name; RrDevice device; } RrDeviceNamed;
typedef struct RrCounter { int32_t n; } RrCounter;
typedef struct RrCmd { RrView name; RrCounter *counter; } RrCmd;
typedef struct RrItem { int32_t k; RrInner *inner; } RrItem;
typedef struct RrItemList { int32_t tag; size_t itemsCount; const RrItem *items; } RrItemList;
typedef struct RrItemSpan { RrItem *items; size_t count; } RrItemSpan;
typedef struct RrBase { int32_t kind; RrView name; } RrBase;
typedef struct RrExt { RrBase base; int32_t extra; } RrExt;
typedef struct RrLinked { int32_t k; const RrBase *link; } RrLinked;
typedef struct RrUd { void *ud; int32_t k; } RrUd;
typedef struct RrNamedUd { RrView name; RrUd inner; } RrNamedUd;
typedef struct RrMaterial { float r; } RrMaterial;
typedef struct RrMesh { int32_t count; RrMaterial *mat; } RrMesh;
typedef struct RrScene { int32_t id; RrMesh *mesh; } RrScene;
typedef void (*RrJobCallback)(RrView message, void *userdata1, void *userdata2);
typedef struct RrCount { int32_t n; RrQ *leaf; } RrCount;
typedef struct RrJob { RrJobCallback callback; void *userdata; void *userparam; RrCount *count; } RrJob;
typedef struct RrNode { int32_t v; struct RrNode *next; } RrNode;
typedef struct RrCycleA { int32_t k; struct RrCycleB *b; } RrCycleA;
typedef struct RrCycleB { int32_t k; RrCycleA *a; } RrCycleB;
typedef struct RrFt { float m[4]; int32_t k; } RrFt;
typedef struct RrDMesh { int32_t tag; size_t vertsCount; float *verts; } RrDMesh;
typedef struct RrDScene { int32_t id; RrDMesh *mesh; } RrDScene;
typedef struct RrNLeaf { int32_t k; } RrNLeaf;
typedef struct RrNMid { int32_t m; size_t leavesCount; const RrNLeaf *leaves; } RrNMid;
typedef struct RrNTop { int32_t t; size_t midsCount; RrNMid *mids; } RrNTop;
typedef struct RrNView { int32_t t; size_t midsCount; const RrNMid *mids; } RrNView;
typedef struct RrScMaterial { float r; } RrScMaterial;
typedef struct RrScMesh { int32_t n; RrScMaterial *material; } RrScMesh;
typedef struct RrScEntity { int32_t id; RrScMesh *mesh; } RrScEntity;
typedef struct RrScScene { int32_t t; size_t entitiesCount; const RrScEntity *entities; } RrScScene;
typedef struct RrSMid { int32_t m; size_t leavesCount; const int32_t *leaves; } RrSMid;
typedef struct RrSTop { int32_t t; size_t midsCount; RrSMid *mids; } RrSTop;
typedef struct RrFp { int32_t x; } RrFp;
typedef struct RrFr { float m[4]; RrFp *p; } RrFr;
typedef struct RrFb { float m[4]; } RrFb;
typedef struct RrBMesh { float bounds[4]; RrMaterial *mat; } RrBMesh;
typedef struct RrBScene { int32_t id; RrBMesh *mesh; } RrBScene;
typedef struct RrTr { float m[4]; RrFp *p; } RrTr;
typedef int32_t RrModeC;
/* @subscript-cenum RrModeC RrMode */
typedef struct RrRec { int32_t tag; RrModeC mode; size_t modesCount; RrModeC *modes; } RrRec;
typedef struct RrRecC { int32_t tag; RrModeC mode; size_t modesCount; const RrModeC *modes; } RrRecC;
typedef struct RrHBase { int32_t kind; } RrHBase;
typedef struct RrHExt { RrHBase base; RrView name; } RrHExt;
typedef struct RrHHolder { int32_t k; const RrHBase *link; } RrHHolder;
typedef struct RrGBase { int32_t kind; } RrGBase;
typedef struct RrGExt { RrGBase base; int32_t extra; } RrGExt;
typedef struct RrGHolder { int32_t k; const RrGBase *link; } RrGHolder;
typedef struct RrPMesh { float bounds[4]; size_t idsCount; const uint32_t *ids; } RrPMesh;
typedef struct RrPNamed { RrView name; float m[4]; } RrPNamed;
typedef struct RrPJob { RrJobCallback callback; void *userdata; void *userparam; int32_t prio; } RrPJob;
typedef struct RrPBody { float x; float y; void *user; } RrPBody;
typedef struct RrPWorld { int32_t n; RrPBody *player; } RrPWorld;
typedef struct RrCNode { int32_t v; const struct RrCNode *next; } RrCNode;
typedef struct RrVec3 { float x; float y; float z; } RrVec3;
typedef struct RrVMesh { int32_t count; } RrVMesh;
typedef struct RrEntity { RrVec3 pos; RrVMesh *mesh; } RrEntity;
typedef struct RrVec2 { float x; float y; } RrVec2;
typedef struct RrLabel { RrVec2 pos; RrView text; } RrLabel;
typedef struct RrMatrix { float m0, m4, m8, m12, m1, m5, m9, m13, m2, m6, m10, m14, m3, m7, m11, m15; } RrMatrix;
typedef struct RrRMesh { int32_t vertexCount; } RrRMesh;
typedef struct RrModel { RrMatrix transform; int32_t meshTotal; RrRMesh *meshes; } RrModel;
typedef struct RrWExt { RrVec3 pos; int32_t extra; RrVMesh *mesh; } RrWExt;
typedef struct RrWHolder { int32_t k; RrVec3 *link; } RrWHolder;
typedef struct RrIV2 { int32_t x; int32_t y; } RrIV2;
typedef struct RrSpr { int32_t id; } RrSpr;
typedef struct RrLab { RrIV2 pos; RrView text; } RrLab;
typedef struct RrTile { RrIV2 pos; RrIV2 size; RrSpr *s; } RrTile;
typedef struct RrNodeV { RrVec3 pos; struct RrNodeV *parent; } RrNodeV;

void subReadRootHolderFill(RrHolder *out);
int32_t subReadRootHolderSum(const RrHolder *holder);
void subReadRootOuterTouch(RrOuter outer);
int32_t subReadRootOuterSum(RrOuterConst outer);
void subReadRootNamedFill(RrNamed *out);
void subReadRootDeviceNamedFill(RrDeviceNamed *out);
RrDevice subReadRootDevice(int32_t id);
int32_t subReadRootDeviceId(RrDevice device);
void subReadRootCmdRun(const RrCmd *cmd);
void subReadRootOuterBump(const RrOuter *outer);
void subReadRootItemListFill(RrItemList *out);
void subReadRootItemSpanTouch(RrItemSpan span);
int32_t subReadRootLinkedUse(const RrLinked *linked);
int32_t subReadRootExtUse(const RrExt *ext);
void subReadRootNamedUdFill(RrNamedUd *out);
void subReadRootUdFill(RrUd *out);
int32_t subReadRootRender(const RrScene *scene);
int32_t subReadRootRenderConst(const RrScene *scene);
void subReadRootJobRun(const RrJob *job);
void subReadRootJobSet(const RrJob *job);
void subReadRootNodeBump(RrNode *node);
int32_t subReadRootCycleUse(const RrCycleA *a);
int32_t subReadRootFtSum(RrFt t);
int32_t subReadRootFtSumP(const RrFt *t);
void subReadRootSceneDeform(const RrDScene *scene);
void subReadRootNWalk(const RrNTop *top);
int32_t subReadRootNSum(const RrNView *view);
int32_t subReadRootRenderScene(const RrScScene *s);
void subReadRootSWalk(const RrSTop *top);
RrFr subReadRootFrGet(void);
RrFb subReadRootFbGet(void);
int32_t subReadRootBoundsRender(const RrBScene *scene);
int32_t subReadRootTrSum(const RrTr *t);
int32_t subReadRootTrVal(RrTr t);
void subReadRootTrFill(RrTr *t);
void subReadRootRecFill(RrRec *r);
void subReadRootRecTouch(RrRec r);
int32_t subReadRootRecCGet(const RrRecC *r);
int32_t subReadRootHUse(const RrHHolder *h);
int32_t subReadRootGUse(const RrGHolder *h);
int32_t subReadRootPDraw(const RrPMesh *m);
int32_t subReadRootPDrawV(RrPMesh m);
int32_t subReadRootPNamedUse(const RrPNamed *n);
void subReadRootPSubmit(RrPJob *job);
void subReadRootPStep(RrPWorld *w);
int32_t subReadRootCSum(const RrCNode *n);
void subReadRootCross(const RrVec3 *a, const RrVec3 *b, RrVec3 *out);
void subReadRootMousePos(RrVec2 *out);
int32_t subReadRootLabelLen(const RrLabel *label);
int32_t subReadRootDrawMeshInstanced(RrRMesh mesh, const RrMatrix *transforms, int32_t instances);
int32_t subReadRootLinkedExt(const RrLinked *linked);
void subReadRootWTouch(RrWHolder *h);
int32_t subReadRootWRead(const RrWHolder *h);
RrIV2* subReadRootIvAt(int32_t i);
void subReadRootIvSet(int32_t i, int32_t x, int32_t y);
int32_t subReadRootIvSum(const RrIV2 *p);
void subReadRootIvBump(RrIV2 *p);
int32_t subReadRootLabLen(const RrLab *l);

#endif
