//! The runtime symbol table the dev JIT binds by address.
//!
//! The ship tier resolves the same names from the runtime static library
//! at link time, so one list serves both tiers.

use cranelift_jit::JITBuilder;
use subscript_runtime::{exception, ffi, registration};

macro_rules! runtime_symbols {
    ($($name:ident),+ $(,)?) => {
        &[$((stringify!($name), ffi::$name as *const u8)),+]
    };
}

/// Registers every runtime symbol the lowering imports.
///
/// The dev tier binds them by address; the ship tier resolves the same
/// names from the runtime static library at link time. The macro derives
/// each name/address pair from one FFI identifier.
pub(crate) fn register_runtime(builder: &mut JITBuilder) {
    let symbols: &[(&str, *const u8)] = runtime_symbols!(
        subscript_rt_print,
        subscript_rt_collect,
        subscript_rt_collect_at,
        subscript_rt_alloc,
        subscript_rt_globals_init,
        subscript_rt_boundary_scratch_mark,
        subscript_rt_boundary_scratch_alloc,
        subscript_rt_boundary_scratch_release,
        subscript_rt_async_kick,
        subscript_rt_async_start,
        subscript_rt_async_register,
        subscript_rt_async_register_uncounted,
        subscript_rt_async_all,
        subscript_rt_async_host_operation,
        subscript_rt_file_operation,
        subscript_rt_task_group,
        subscript_rt_async_park,
        subscript_rt_async_await,
        subscript_rt_async_await_owned,
        subscript_rt_async_missing_completion,
        subscript_rt_async_retain,
        subscript_rt_async_release,
        subscript_rt_counted_value,
        subscript_rt_counted_array_operation,
        subscript_rt_async_release_array,
        subscript_rt_async_retain_array,
        subscript_rt_async_is_stale,
        subscript_rt_async_complete,
        subscript_rt_async_result_uncounted,
        subscript_rt_async_result_counted,
        subscript_rt_delete,
        subscript_rt_trap,
        subscript_rt_trap_index_out_of_bounds,
        subscript_rt_trap_wire_enum,
        subscript_rt_root_add,
        subscript_rt_shadow_push,
        subscript_rt_shadow_pop,
        subscript_rt_str_lit,
        subscript_rt_str_from_view,
        subscript_rt_str_len,
        subscript_rt_str_concat,
        subscript_rt_str_slice,
        subscript_rt_str_eq,
        subscript_rt_fmt_i32,
        subscript_rt_fmt_u32,
        subscript_rt_fmt_i64,
        subscript_rt_fmt_u64,
        subscript_rt_fmt_f32,
        subscript_rt_fmt_f64,
        subscript_rt_fmt_bool,
        subscript_rt_error_to_string,
        subscript_rt_encode_uri,
        subscript_rt_encode_uri_component,
        subscript_rt_decode_uri,
        subscript_rt_decode_uri_component,
        subscript_rt_decode_uri_failure,
        subscript_rt_decode_uri_component_failure,
        subscript_rt_json_begin,
        subscript_rt_json_begin_tracked,
        subscript_rt_json_finish,
        subscript_rt_json_raw,
        subscript_rt_json_str,
        subscript_rt_json_i32,
        subscript_rt_json_u32,
        subscript_rt_json_i64,
        subscript_rt_json_u64,
        subscript_rt_json_f32,
        subscript_rt_json_f64,
        subscript_rt_json_bool,
        subscript_rt_json_date,
        subscript_rt_json_null,
        subscript_rt_json_visit,
        subscript_rt_json_leave,
        subscript_rt_json_parse_begin,
        subscript_rt_json_parse_end,
        subscript_rt_json_parse_root,
        subscript_rt_json_parse_is_kind,
        subscript_rt_json_parse_number_fits,
        subscript_rt_json_parse_number,
        subscript_rt_json_parse_integer,
        subscript_rt_json_parse_bool,
        subscript_rt_json_parse_string,
        subscript_rt_json_parse_array_len,
        subscript_rt_json_parse_array_get,
        subscript_rt_json_parse_object_get,
        subscript_rt_json_parse_failure,
        subscript_rt_f16_from_f64,
        subscript_rt_f16_to_f64,
        subscript_rt_fmod,
        subscript_rt_array_new,
        subscript_rt_array_with_capacity,
        subscript_rt_array_from_bytes,
        subscript_rt_array_byte_range,
        subscript_rt_array_len,
        subscript_rt_array_push,
        subscript_rt_array_pop,
        subscript_rt_array_ptr,
        subscript_rt_assoc_iter_begin,
        subscript_rt_assoc_iter_copy,
        subscript_rt_assoc_iter_end,
        subscript_rt_str_iter_code_point,
        subscript_rt_array_spread_array,
        subscript_rt_array_spread_fixed,
        subscript_rt_array_spread_assoc,
        subscript_rt_array_spread_string,
        subscript_rt_set_from_array,
        subscript_rt_set_from_fixed,
        subscript_rt_set_from_assoc,
        subscript_rt_set_from_string,
        subscript_rt_str_data,
        subscript_rt_array_data,
        subscript_rt_cb_bind,
        subscript_rt_cb_trampoline,
        subscript_rt_math_abs,
        subscript_rt_math_acos,
        subscript_rt_math_acosh,
        subscript_rt_math_asin,
        subscript_rt_math_asinh,
        subscript_rt_math_atan,
        subscript_rt_math_atanh,
        subscript_rt_math_cbrt,
        subscript_rt_math_ceil,
        subscript_rt_math_cos,
        subscript_rt_math_cosh,
        subscript_rt_math_exp,
        subscript_rt_math_expm1,
        subscript_rt_math_floor,
        subscript_rt_math_log,
        subscript_rt_math_log1p,
        subscript_rt_math_log10,
        subscript_rt_math_log2,
        subscript_rt_math_round,
        subscript_rt_math_sign,
        subscript_rt_math_sin,
        subscript_rt_math_sinh,
        subscript_rt_math_sqrt,
        subscript_rt_math_tan,
        subscript_rt_math_tanh,
        subscript_rt_math_trunc,
        subscript_rt_math_atan2,
        subscript_rt_math_hypot,
        subscript_rt_math_pow,
        subscript_rt_math_max,
        subscript_rt_math_min,
        subscript_rt_math_random,
        subscript_rt_math_clz32,
        subscript_rt_math_imul,
        subscript_rt_math_fround,
        subscript_rt_math_f32_to_bits,
        subscript_rt_math_f32_from_bits,
        subscript_rt_num_is_nan,
        subscript_rt_num_is_finite,
        subscript_rt_num_is_integer,
        subscript_rt_num_is_safe_integer,
        subscript_rt_num_parse_int,
        subscript_rt_num_parse_float,
        subscript_rt_num_to_fixed,
        subscript_rt_num_to_string_f32,
        subscript_rt_num_to_string_f64,
        subscript_rt_num_to_exponential,
        subscript_rt_num_to_precision,
        subscript_rt_str_index_of,
        subscript_rt_str_last_index_of,
        subscript_rt_str_includes,
        subscript_rt_str_starts_with,
        subscript_rt_str_ends_with,
        subscript_rt_str_char_code_at,
        subscript_rt_str_split,
        subscript_rt_str_trim,
        subscript_rt_str_trim_start,
        subscript_rt_str_trim_end,
        subscript_rt_str_repeat,
        subscript_rt_str_pad_start,
        subscript_rt_str_pad_end,
        subscript_rt_str_to_upper,
        subscript_rt_str_to_lower,
        subscript_rt_str_replace,
        subscript_rt_str_replace_all,
        subscript_rt_str_substring,
        subscript_rt_str_substr,
        subscript_rt_str_char_at,
        subscript_rt_str_at,
        subscript_rt_str_code_point_at,
        subscript_rt_arr_index_of,
        subscript_rt_arr_last_index_of,
        subscript_rt_arr_includes,
        subscript_rt_arr_join,
        subscript_rt_arr_slice,
        subscript_rt_arr_fill,
        subscript_rt_arr_reverse,
        subscript_rt_arr_concat,
        subscript_rt_arr_for_each,
        subscript_rt_arr_map,
        subscript_rt_arr_filter,
        subscript_rt_arr_reduce,
        subscript_rt_arr_some,
        subscript_rt_arr_every,
        subscript_rt_arr_find_index,
        subscript_rt_arr_at,
        subscript_rt_arr_find,
        subscript_rt_arr_find_last,
        subscript_rt_arr_find_last_index,
        subscript_rt_arr_flat_map,
        subscript_rt_arr_sort,
        subscript_rt_arr_reduce_right,
        subscript_rt_arr_splice,
        subscript_rt_arr_shift,
        subscript_rt_arr_unshift,
        subscript_rt_arr_copy_within,
        subscript_rt_fixed_arr_for_each,
        subscript_rt_fixed_arr_map,
        subscript_rt_fixed_arr_filter,
        subscript_rt_fixed_arr_reduce,
        subscript_rt_fixed_arr_some,
        subscript_rt_fixed_arr_every,
        subscript_rt_fixed_arr_find_index,
        subscript_rt_fixed_arr_reduce_right,
        subscript_rt_map_new,
        subscript_rt_map_describe,
        subscript_rt_object_describe,
        subscript_rt_map_from_assoc,
        subscript_rt_assoc_size,
        subscript_rt_assoc_has,
        subscript_rt_assoc_delete,
        subscript_rt_assoc_clear,
        subscript_rt_map_get,
        subscript_rt_map_get_or,
        subscript_rt_map_set,
        subscript_rt_map_for_each,
        subscript_rt_map_group_by,
        subscript_rt_set_new,
        subscript_rt_set_add,
        subscript_rt_set_for_each,
        subscript_rt_set_union,
        subscript_rt_set_intersection,
        subscript_rt_set_difference,
        subscript_rt_set_symmetric_difference,
        subscript_rt_set_is_subset_of,
        subscript_rt_set_is_superset_of,
        subscript_rt_set_is_disjoint_from,
        subscript_rt_date_utc,
        subscript_rt_date_new,
        subscript_rt_date_now,
        subscript_rt_date_get,
        subscript_rt_date_to_iso,
        subscript_rt_date_to_utc_string,
        subscript_rt_worker_spawn,
        subscript_rt_worker_post,
        subscript_rt_worker_poll,
        subscript_rt_worker_close,
        subscript_rt_worker_join,
        subscript_rt_worker_inbox_wait,
        subscript_rt_worker_inbox_poll,
        subscript_rt_worker_outbox_post,
        subscript_rt_regex_new,
        subscript_rt_regex_test,
        subscript_rt_regex_source,
        subscript_rt_regex_flags,
        subscript_rt_regex_global,
        subscript_rt_regex_ignore_case,
        subscript_rt_regex_multiline,
        subscript_rt_regex_dot_all,
        subscript_rt_regex_unicode,
        subscript_rt_regex_has_indices,
        subscript_rt_regex_sticky,
        subscript_rt_regex_to_string,
        subscript_rt_regex_search,
        subscript_rt_regex_replace,
        subscript_rt_regex_replace_all,
        subscript_rt_regex_split,
        subscript_rt_regex_match_start,
        subscript_rt_regex_match_end,
    );
    for (name, address) in symbols {
        builder.symbol(*name, *address);
    }
    // §111 rule 4. These two live with their area in
    // `subscript_runtime::registration`, so the `ffi::` macro above
    // cannot name them.
    for (name, address) in [
        (
            "subscript_rt_cb_register",
            registration::subscript_rt_cb_register as *const u8,
        ),
        (
            "subscript_rt_cb_registration_trampoline",
            registration::subscript_rt_cb_registration_trampoline as *const u8,
        ),
        // compiler.md §115: the exception entries live with their area.
        (
            "subscript_rt_exception_throw",
            exception::subscript_rt_exception_throw as *const u8,
        ),
        (
            "subscript_rt_exception_catch",
            exception::subscript_rt_exception_catch as *const u8,
        ),
        (
            "subscript_rt_exception_settle",
            exception::subscript_rt_exception_settle as *const u8,
        ),
        (
            "subscript_rt_exception_message",
            exception::subscript_rt_exception_message as *const u8,
        ),
        (
            "subscript_rt_exception_position",
            exception::subscript_rt_exception_position as *const u8,
        ),
        (
            "subscript_rt_exception_restore",
            exception::subscript_rt_exception_restore as *const u8,
        ),
        (
            "subscript_rt_exception_park",
            exception::subscript_rt_exception_park as *const u8,
        ),
        (
            "subscript_rt_exception_resume",
            exception::subscript_rt_exception_resume as *const u8,
        ),
        (
            "subscript_rt_async_complete_exception",
            exception::subscript_rt_async_complete_exception as *const u8,
        ),
    ] {
        builder.symbol(name, address);
    }
}
