//! Generator for the embedding host's C header.
//!
//! The declarations are read from the runtime's Rust `extern "C"`
//! definitions. Unsupported Rust types fail generation instead of
//! producing an ABI guess.

const HOST_OPERATION_SOURCE: &str = include_str!("context/host_operation.rs");

const FFI_SOURCE: &str = include_str!("ffi.rs");
const TASK_SOURCE: &str = include_str!("context/async_inspection.rs");
const CONTEXT_SOURCE: &str = include_str!("context.rs");
const WORKER_SOURCE: &str = include_str!("worker.rs");

#[derive(Debug)]
struct Function {
    name: String,
    params: Vec<(String, String)>,
    result: String,
}

/// Renders the generated host C header from the runtime's Rust
/// declarations.
///
/// # Errors
///
/// Returns an error when a host function or callback declaration cannot
/// be parsed or contains a Rust type with no explicit C spelling.
pub fn render() -> Result<String, String> {
    let observer_docs = docs_for(CONTEXT_SOURCE, "pub type TrapObserver")?;
    let observer = parse_fn_type(CONTEXT_SOURCE, "TrapObserver")?;
    let print_observer_docs = docs_for(CONTEXT_SOURCE, "pub type PrintObserver")?;
    let print_observer = parse_fn_type(CONTEXT_SOURCE, "PrintObserver")?;
    let diagnostics_observer_docs = docs_for(CONTEXT_SOURCE, "pub type DiagnosticsObserver")?;
    let diagnostics_observer = parse_fn_type(CONTEXT_SOURCE, "DiagnosticsObserver")?;
    let allocation_visitor_docs = docs_for(CONTEXT_SOURCE, "pub type AllocationVisitor")?;
    let allocation_visitor = parse_fn_type(CONTEXT_SOURCE, "AllocationVisitor")?;
    let entry_docs = docs_for(CONTEXT_SOURCE, "pub type ScriptMainEntry")?;
    let entry = parse_fn_type(CONTEXT_SOURCE, "ScriptMainEntry")?;
    let worker_init_docs = docs_for(WORKER_SOURCE, "pub type WorkerInit")?;
    let worker_init = parse_fn_type(WORKER_SOURCE, "WorkerInit")?;
    let worker_entry_docs = docs_for(WORKER_SOURCE, "pub type WorkerEntry")?;
    let worker_entry = parse_fn_type(WORKER_SOURCE, "WorkerEntry")?;
    let freed_handle_diagnostics_docs = docs_for(
        FFI_SOURCE,
        "pub unsafe extern \"C\" fn subscript_rt_ctx_set_freed_handle_diagnostics",
    )?;
    let print_observer_setter_docs = docs_for(
        FFI_SOURCE,
        "pub unsafe extern \"C\" fn subscript_rt_ctx_set_print_observer",
    )?;
    let diagnostics_observer_setter_docs = docs_for(
        FFI_SOURCE,
        "pub unsafe extern \"C\" fn subscript_rt_ctx_set_diagnostics_observer",
    )?;
    let binding_count_advisory_setter_docs = docs_for(
        FFI_SOURCE,
        "pub unsafe extern \"C\" fn subscript_rt_ctx_set_binding_count_advisory",
    )?;
    let callback_release_docs = docs_for(
        FFI_SOURCE,
        "pub unsafe extern \"C\" fn subscript_rt_ctx_callback_release",
    )?;
    let async_pending_docs = docs_for(
        FFI_SOURCE,
        "pub unsafe extern \"C\" fn subscript_rt_ctx_async_pending",
    )?;
    let async_step_docs = docs_for(
        FFI_SOURCE,
        "pub unsafe extern \"C\" fn subscript_rt_ctx_async_step",
    )?;
    let async_step_budget_docs = docs_for(
        FFI_SOURCE,
        "pub unsafe extern \"C\" fn subscript_rt_ctx_async_step_budget",
    )?;
    let async_unfinished_docs = docs_for(
        FFI_SOURCE,
        "pub unsafe extern \"C\" fn subscript_rt_ctx_async_unfinished",
    )?;
    let task_visitor_docs = docs_for(TASK_SOURCE, "pub type AsyncTaskVisitor")?;
    let task_visitor = parse_fn_type(TASK_SOURCE, "AsyncTaskVisitor")?;
    let task_visit_docs = docs_for(
        FFI_SOURCE,
        "pub unsafe extern \"C\" fn subscript_rt_ctx_visit_async_tasks",
    )?;
    let mut functions = parse_functions(FFI_SOURCE, "subscript_rt_ctx_")?;
    functions.extend(parse_functions(FFI_SOURCE, "subscript_rt_complete_")?);
    functions.sort_by(|a, b| a.name.cmp(&b.name));
    // §111 rule 5a. The registration reader is host API, and its name
    // carries no `subscript_rt_ctx_` prefix, so the generator names it.
    // The other `subscript_rt_cb_` entries are generated-code API and
    // stay out of this header.
    let mut registration_functions =
        parse_functions(FFI_SOURCE, "subscript_rt_cb_registration_context")?;
    registration_functions.sort_by(|a, b| a.name.cmp(&b.name));
    let mut worker_functions = parse_functions(FFI_SOURCE, "subscript_rt_worker_")?;
    worker_functions.sort_by(|a, b| a.name.cmp(&b.name));

    let mut out = String::new();
    out.push_str(
        "/* DO NOT EDIT. Generated by `cargo run --offline -p subscript-runtime \
         --bin generate-host-header`.\n",
    );
    out.push_str(
        " * Source of truth: runtime/src/ffi.rs, runtime/src/context.rs, and runtime/src/worker.rs.\n",
    );
    out.push_str(" */\n");
    out.push_str("#ifndef SUBSCRIPT_RUNTIME_H\n");
    out.push_str("#define SUBSCRIPT_RUNTIME_H\n\n");
    out.push_str("#include <stdint.h>\n#include <stddef.h>\n\n");
    out.push_str("/* Recommended freed-handle diagnostics retention budget. The runtime does\n");
    out.push_str(" * not treat this value specially. */\n");
    out.push_str(&format!(
        "#define SUBSCRIPT_RT_FREED_HANDLE_DIAGNOSTICS_DEFAULT_MAX_RETAINED_BYTES \
         UINT64_C({})\n\n",
        crate::FREED_HANDLE_DIAGNOSTICS_DEFAULT_MAX_RETAINED_BYTES
    ));
    out.push_str("/* Diagnostics advisory kinds. */\n");
    out.push_str(&format!(
        "#define SUBSCRIPT_RT_DIAGNOSTICS_ADVISORY_CALLBACK_USERDATA_FREE UINT32_C({})\n",
        crate::DIAGNOSTICS_ADVISORY_CALLBACK_USERDATA_FREE
    ));
    out.push_str(&format!(
        "#define SUBSCRIPT_RT_DIAGNOSTICS_ADVISORY_BINDING_COUNT UINT32_C({})\n\n",
        crate::DIAGNOSTICS_ADVISORY_BINDING_COUNT
    ));
    out.push_str("#ifdef __cplusplus\n");
    out.push_str("extern \"C\" {\n");
    out.push_str("#endif\n\n");
    out.push_str("typedef struct subscript_rt_context subscript_rt_context;\n\n");
    out.push_str("typedef struct subscript_rt_worker subscript_rt_worker;\n");
    out.push_str("typedef struct subscript_rt_worker_inbox subscript_rt_worker_inbox;\n");
    out.push_str("typedef struct subscript_rt_worker_outbox subscript_rt_worker_outbox;\n\n");
    out.push_str("typedef struct subscript_rt_worker_message_descriptor {\n");
    out.push_str("    uint64_t payload_size;\n");
    out.push_str("    uint64_t string_slot_count;\n");
    out.push_str("    const uint64_t* string_slot_offsets;\n");
    out.push_str("} subscript_rt_worker_message_descriptor;\n\n");
    out.push_str(&format!(
        "/* Null conversion trap kinds (compiler.md §124). */\n#define SUBSCRIPT_RT_TRAP_NULL_NARROWING {}u\n#define SUBSCRIPT_RT_TRAP_SHARED_NULL_NARROWING {}u\n\n",
        crate::TrapKind::NullNarrowing as u32,
        crate::TrapKind::SharedNullNarrowing as u32,
    ));
    out.push_str(&format!(
        "/* Task group trap (compiler.md §170). */\n#define SUBSCRIPT_RT_TRAP_TASK_GROUP {}u\n\n",
        crate::TrapKind::TaskGroup as u32
    ));
    out.push_str(&format!("/* Generator value trap (compiler.md §145). */\n#define SUBSCRIPT_RT_TRAP_GENERATOR_DONE_VALUE {}u\n\n", crate::TrapKind::GeneratorDoneValue as u32));
    push_comment(&mut out, &observer_docs);
    out.push_str("typedef ");
    out.push_str(&c_fn_pointer("subscript_rt_trap_observer", &observer)?);
    out.push_str(";\n\n");
    push_comment(&mut out, &print_observer_docs);
    out.push_str("typedef ");
    out.push_str(&c_fn_pointer(
        "subscript_rt_print_observer",
        &print_observer,
    )?);
    out.push_str(";\n\n");
    push_comment(&mut out, &diagnostics_observer_docs);
    out.push_str("typedef ");
    out.push_str(&c_fn_pointer(
        "subscript_rt_diagnostics_observer",
        &diagnostics_observer,
    )?);
    out.push_str(";\n\n");
    push_comment(&mut out, &allocation_visitor_docs);
    out.push_str("typedef ");
    out.push_str(&c_fn_pointer(
        "subscript_rt_alloc_visitor",
        &allocation_visitor,
    )?);
    out.push_str(";\n\n");
    push_comment_with_c_docs(
        &mut out,
        &entry_docs,
        &[
            "",
            "compiler.md §142 rules 1 and 2:",
            "A handle that the host passes to a script transfers no ownership.",
            "The script can copy the handle, keep it, and use it in a later call.",
            "The host keeps the object valid while any script code of that Context",
            "can use the handle.",
            "A script object that holds the handle keeps nothing alive on the host side.",
            "The language and runtime do not detect use after the host destroys the object.",
        ],
    );
    out.push_str("typedef ");
    out.push_str(&c_fn_pointer("subscript_main_entry", &entry)?);
    out.push_str(";\n\n");
    push_comment(&mut out, &worker_init_docs);
    out.push_str("typedef ");
    out.push_str(&c_fn_pointer("subscript_rt_worker_init", &worker_init)?);
    out.push_str(";\n\n");
    push_comment(&mut out, &worker_entry_docs);
    out.push_str("typedef ");
    out.push_str(&c_fn_pointer("subscript_rt_worker_entry", &worker_entry)?);
    out.push_str(";\n\n");
    out.push_str("/* The program header declares the entry module's checked host API. */\n");
    out.push_str(&c_function("subscript_init", &entry)?);
    out.push_str(";\n\n");

    push_comment(
        &mut out,
        &docs_for(HOST_OPERATION_SOURCE, "pub struct CompletionEndpoint")?,
    );
    out.push_str("typedef struct subscript_rt_completion {\n");
    for field in ["context_id", "operation_id"] {
        push_comment(
            &mut out,
            &docs_for(HOST_OPERATION_SOURCE, &format!("pub {field}:"))?,
        );
        out.push_str(&format!("    uint64_t {field};\n"));
    }
    out.push_str("} subscript_rt_completion;\n\n");
    push_comment(
        &mut out,
        &docs_for(HOST_OPERATION_SOURCE, "pub enum CompletionStatus")?,
    );
    out.push_str("typedef enum subscript_rt_completion_status {\n");
    use crate::context::CompletionStatus;
    for (rust, c, value) in [
        ("Ok", "OK", CompletionStatus::Ok),
        ("Stale", "STALE", CompletionStatus::Stale),
        ("Duplicate", "DUPLICATE", CompletionStatus::Duplicate),
        ("Mismatch", "MISMATCH", CompletionStatus::Mismatch),
        ("Trapped", "TRAPPED", CompletionStatus::Trapped),
        ("InvalidUtf8", "INVALID_UTF8", CompletionStatus::InvalidUtf8),
        ("TooLarge", "TOO_LARGE", CompletionStatus::TooLarge),
    ] {
        push_comment(
            &mut out,
            &docs_for(HOST_OPERATION_SOURCE, &format!("{rust} ="))?,
        );
        out.push_str(&format!(
            "    SUBSCRIPT_RT_COMPLETION_{c} = {},\n",
            value as u32
        ));
    }
    out.push_str("} subscript_rt_completion_status;\n\n");

    out.push_str("typedef struct subscript_rt_async_step_report {\n");
    for field in ["dispatched", "pending", "unfinished", "budget_exhausted"] {
        out.push_str(&format!("    uint64_t {field};\n"));
    }
    out.push_str("} subscript_rt_async_step_report;\n\n");

    out.push_str("/* Registered task record (compiler.md §169). */\n");
    out.push_str("typedef struct subscript_rt_async_task_info {\n");
    for field in ["task_id", "awaited_task_id"] {
        out.push_str(&format!("    uint64_t {field};\n"));
    }
    for field in [
        "state",
        "kind",
        "function_pos_id",
        "await_pos_id",
        "create_pos_id",
        "reserved",
    ] {
        out.push_str(&format!("    uint32_t {field};\n"));
    }
    out.push_str("} subscript_rt_async_task_info;\n\n");
    push_comment(&mut out, &task_visitor_docs);
    out.push_str("typedef ");
    out.push_str(&c_fn_pointer(
        "subscript_rt_async_task_visitor",
        &task_visitor,
    )?);
    out.push_str(";\n\n");

    for function in &functions {
        if function.name.starts_with("subscript_rt_complete_") {
            let declaration = format!("pub unsafe extern \"C\" fn {}", function.name);
            push_comment(&mut out, &docs_for(FFI_SOURCE, &declaration)?);
        }
        if function.name == "subscript_rt_ctx_visit_async_tasks" {
            push_comment(&mut out, &task_visit_docs);
        }
        if function.name == "subscript_rt_ctx_set_freed_handle_diagnostics" {
            push_comment(&mut out, &freed_handle_diagnostics_docs);
        }
        if function.name == "subscript_rt_ctx_set_print_observer" {
            push_comment(&mut out, &print_observer_setter_docs);
        }
        if function.name == "subscript_rt_ctx_set_diagnostics_observer" {
            push_comment(&mut out, &diagnostics_observer_setter_docs);
        }
        if function.name == "subscript_rt_ctx_set_binding_count_advisory" {
            push_comment(&mut out, &binding_count_advisory_setter_docs);
        }
        if function.name == "subscript_rt_ctx_callback_release" {
            push_comment(&mut out, &callback_release_docs);
        }
        if function.name == "subscript_rt_ctx_async_pending" {
            push_comment(&mut out, &async_pending_docs);
        }
        if function.name == "subscript_rt_ctx_async_step" {
            push_comment(&mut out, &async_step_docs);
        }
        if function.name == "subscript_rt_ctx_async_step_budget" {
            push_comment(&mut out, &async_step_budget_docs);
        }
        if function.name == "subscript_rt_ctx_async_unfinished" {
            push_comment(&mut out, &async_unfinished_docs);
        }
        out.push_str(&c_function(&function.name, function)?);
        out.push_str(";\n");
    }
    out.push('\n');
    for function in &registration_functions {
        let declaration = format!("pub unsafe extern \"C\" fn {}", function.name);
        let docs = docs_for(FFI_SOURCE, &declaration)?;
        push_comment(&mut out, &docs);
        out.push_str(&c_function(&function.name, function)?);
        out.push_str(";\n");
    }
    out.push('\n');
    for function in &worker_functions {
        let declaration = format!("pub unsafe extern \"C\" fn {}", function.name);
        let docs = docs_for(FFI_SOURCE, &declaration)?;
        push_comment(&mut out, &docs);
        out.push_str(&c_function(&function.name, function)?);
        out.push_str(";\n");
    }
    out.push_str("\n#ifdef __cplusplus\n");
    out.push_str("} /* extern \"C\" */\n");
    out.push_str("#endif\n\n");
    out.push_str("#endif /* SUBSCRIPT_RUNTIME_H */\n");
    Ok(out)
}

fn docs_for(source: &str, declaration: &str) -> Result<Vec<String>, String> {
    let lines: Vec<&str> = source.lines().collect();
    let index = lines
        .iter()
        .position(|line| line.trim_start().starts_with(declaration))
        .ok_or_else(|| format!("host header: missing Rust declaration `{declaration}`"))?;
    let mut docs = Vec::new();
    for line in lines[..index].iter().rev() {
        let trimmed = line.trim_start();
        if trimmed.starts_with("#[") {
            continue;
        }
        let Some(doc) = trimmed.strip_prefix("///") else {
            break;
        };
        docs.push(doc.strip_prefix(' ').unwrap_or(doc).to_string());
    }
    docs.reverse();
    if docs.is_empty() {
        return Err(format!(
            "host header: Rust declaration `{declaration}` has no documentation"
        ));
    }
    Ok(docs)
}

fn push_comment(out: &mut String, docs: &[String]) {
    push_comment_with_c_docs(out, docs, &[]);
}

fn push_comment_with_c_docs(out: &mut String, docs: &[String], c_docs: &[&str]) {
    out.push_str("/**\n");
    for line in docs
        .iter()
        .map(|line| rewrite_context_c_type(line))
        .chain(c_docs.iter().map(|line| (*line).to_owned()))
    {
        out.push_str(" *");
        if !line.is_empty() {
            out.push(' ');
            out.push_str(&line);
        }
        out.push('\n');
    }
    out.push_str(" */\n");
}

fn rewrite_context_c_type(text: &str) -> String {
    const FROM: &str = "Context";
    const TO: &str = "subscript_rt_context";

    let bytes = text.as_bytes();
    let mut out = String::with_capacity(text.len());
    let mut cursor = 0;
    for (start, _) in text.match_indices(FROM) {
        let end = start + FROM.len();
        let left_is_identifier =
            start > 0 && (bytes[start - 1].is_ascii_alphanumeric() || bytes[start - 1] == b'_');
        let right_is_identifier =
            end < bytes.len() && (bytes[end].is_ascii_alphanumeric() || bytes[end] == b'_');
        if left_is_identifier || right_is_identifier {
            continue;
        }
        out.push_str(&text[cursor..start]);
        out.push_str(TO);
        cursor = end;
    }
    out.push_str(&text[cursor..]);
    out
}

fn parse_fn_type(source: &str, name: &str) -> Result<Function, String> {
    let marker = format!("pub type {name}");
    let start = source
        .find(&marker)
        .ok_or_else(|| format!("host header: missing Rust type `{name}`"))?;
    let tail = &source[start..];
    let end = tail
        .find(';')
        .ok_or_else(|| format!("host header: unterminated Rust type `{name}`"))?;
    let declaration = &tail[..end];
    let signature = declaration
        .split_once('=')
        .map(|(_, signature)| signature)
        .ok_or_else(|| format!("host header: malformed Rust type `{name}`"))?;
    parse_signature(name, signature)
}

fn parse_functions(source: &str, prefix: &str) -> Result<Vec<Function>, String> {
    let lines: Vec<&str> = source.lines().collect();
    let mut functions = Vec::new();
    let mut index = 0;
    while index < lines.len() {
        let line = lines[index];
        if !line.contains("extern \"C\" fn") || !line.contains(prefix) {
            index += 1;
            continue;
        }
        let mut declaration = line.trim().to_string();
        while !declaration.contains('{') {
            index += 1;
            let next = lines.get(index).ok_or_else(|| {
                format!("host header: unterminated Rust function near `{declaration}`")
            })?;
            declaration.push(' ');
            declaration.push_str(next.trim());
        }
        let signature = declaration
            .split_once("fn ")
            .map(|(_, signature)| signature)
            .ok_or_else(|| format!("host header: malformed Rust function `{declaration}`"))?;
        let function = parse_signature("", signature)?;
        if function.name.starts_with(prefix) {
            functions.push(function);
        }
        index += 1;
    }
    if functions.is_empty() {
        return Err(format!(
            "host header: no Rust functions with prefix `{prefix}`"
        ));
    }
    Ok(functions)
}

fn parse_signature(fallback_name: &str, signature: &str) -> Result<Function, String> {
    let signature = signature.trim();
    let open = signature
        .find('(')
        .ok_or_else(|| format!("host header: function has no parameter list `{signature}`"))?;
    let name = signature[..open]
        .split_whitespace()
        .last()
        .filter(|name| !name.is_empty())
        .unwrap_or(fallback_name)
        .to_string();
    let mut depth = 0usize;
    let mut close = None;
    for (offset, ch) in signature[open..].char_indices() {
        match ch {
            '(' => depth += 1,
            ')' => {
                depth = depth.saturating_sub(1);
                if depth == 0 {
                    close = Some(open + offset);
                    break;
                }
            }
            _ => {}
        }
    }
    let close = close.ok_or_else(|| {
        format!("host header: function has an unterminated parameter list `{signature}`")
    })?;
    let mut params = Vec::new();
    for param in signature[open + 1..close].split(',') {
        let param = param.trim();
        if param.is_empty() {
            continue;
        }
        let (name, ty) = param
            .split_once(':')
            .ok_or_else(|| format!("host header: unnamed Rust parameter `{param}`"))?;
        params.push((name.trim().to_string(), normalize_type(ty)));
    }
    let tail = signature[close + 1..]
        .split('{')
        .next()
        .unwrap_or_default()
        .trim();
    let result = tail
        .strip_prefix("->")
        .map_or_else(|| "()".to_string(), normalize_type);
    Ok(Function {
        name,
        params,
        result,
    })
}

fn normalize_type(ty: &str) -> String {
    ty.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn c_type(rust: &str) -> Result<&'static str, String> {
    match rust {
        "()" => Ok("void"),
        "usize" => Ok("size_t"),
        "CompletionEndpoint" => Ok("subscript_rt_completion"),
        "CompletionStatus" => Ok("subscript_rt_completion_status"),
        "*const c_void" => Ok("const void*"),
        "*const std::ffi::c_char" => Ok("const char*"),
        "i32" => Ok("int32_t"),
        "i64" => Ok("int64_t"),
        "u32" => Ok("uint32_t"),
        "u64" => Ok("uint64_t"),
        "*const AsyncTaskInfo" => Ok("const subscript_rt_async_task_info*"),
        "Option<AsyncTaskVisitor>" => Ok("subscript_rt_async_task_visitor"),
        "AsyncStepReport" => Ok("subscript_rt_async_step_report"),
        "*mut Context" => Ok("subscript_rt_context*"),
        "*const Context" => Ok("const subscript_rt_context*"),
        "*mut Worker" => Ok("subscript_rt_worker*"),
        "*mut WorkerInbox" => Ok("subscript_rt_worker_inbox*"),
        "*mut WorkerOutbox" => Ok("subscript_rt_worker_outbox*"),
        "*const crate::worker::WorkerMessageDescriptor" => {
            Ok("const subscript_rt_worker_message_descriptor*")
        }
        "*mut u8" => Ok("uint8_t*"),
        "*mut u64" => Ok("uint64_t*"),
        "*const u8" => Ok("const uint8_t*"),
        "*mut c_void" | "*mut std::ffi::c_void" => Ok("void*"),
        "Option<TrapObserver>" => Ok("subscript_rt_trap_observer"),
        "Option<PrintObserver>" => Ok("subscript_rt_print_observer"),
        "Option<DiagnosticsObserver>" => Ok("subscript_rt_diagnostics_observer"),
        "Option<AllocationVisitor>" => Ok("subscript_rt_alloc_visitor"),
        "Option<WorkerInit>" => Ok("subscript_rt_worker_init"),
        "Option<WorkerEntry>" => Ok("subscript_rt_worker_entry"),
        other => Err(format!(
            "host header: Rust type `{other}` has no explicit C spelling"
        )),
    }
}

fn c_params(function: &Function) -> Result<String, String> {
    if function.params.is_empty() {
        return Ok("void".to_string());
    }
    function
        .params
        .iter()
        .map(|(name, ty)| Ok(format!("{} {name}", c_type(ty)?)))
        .collect::<Result<Vec<_>, String>>()
        .map(|params| params.join(", "))
}

fn c_function(name: &str, function: &Function) -> Result<String, String> {
    Ok(format!(
        "{} {name}({})",
        c_type(&function.result)?,
        c_params(function)?
    ))
}

fn c_fn_pointer(name: &str, function: &Function) -> Result<String, String> {
    Ok(format!(
        "{} (*{name})({})",
        c_type(&function.result)?,
        c_params(function)?
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::worker::WorkerMessageDescriptor;

    #[test]
    fn generated_host_header_is_byte_identical() {
        let committed = include_str!("../include/subscript_runtime.h");
        assert_eq!(
            render().expect("render host header").as_bytes(),
            committed.as_bytes(),
            "the committed host header drifted; regenerate with \
             `cargo run --offline -p subscript-runtime --bin generate-host-header`"
        );
    }

    #[test]
    fn generated_host_header_documents_host_handle_lifetime() {
        let header = render().expect("render host header");
        assert_eq!(header.matches("compiler.md §142 rules 1 and 2:").count(), 1);
        assert!(header.contains(
            r#"/**
 * C calling convention shared by the module initializer (`subscript_init`) and every
 * supported host export.
 *
 * A host that may clear traps brackets each call with
 * `subscript_rt_ctx_enter_script` and `subscript_rt_ctx_exit_script`.
 *
 * An ordinary run entry uses `subscript_export_main`; a host-owned entry may instead
 * drive other zero-argument `void` exports using the symbol
 * `subscript_export_<name>` and this same C signature.
 *
 * compiler.md §142 rules 1 and 2:
 * A handle that the host passes to a script transfers no ownership.
 * The script can copy the handle, keep it, and use it in a later call.
 * The host keeps the object valid while any script code of that Context
 * can use the handle.
 * A script object that holds the handle keeps nothing alive on the host side.
 * The language and runtime do not detect use after the host destroys the object.
 */
typedef void (*subscript_main_entry)(subscript_rt_context* ctx);
"#
        ));
    }

    #[test]
    fn generated_host_header_names_the_generator_value_trap() {
        let header = render().expect("render host header");
        assert!(header.contains("#define SUBSCRIPT_RT_TRAP_GENERATOR_DONE_VALUE 32u"));
    }

    #[test]
    fn generated_host_header_distinguishes_null_conversion_kinds() {
        let header = render().expect("render host header");
        assert!(header.contains("#define SUBSCRIPT_RT_TRAP_NULL_NARROWING 4u"));
        assert!(header.contains("#define SUBSCRIPT_RT_TRAP_SHARED_NULL_NARROWING 31u"));
    }

    #[test]
    fn generated_host_header_carries_the_observer_aliasing_rule() {
        let header = render().expect("render host header");
        assert!(header
            .contains("calling any `subscript_rt_*` API that takes that subscript_rt_context"));
        assert!(header.contains("pointer smuggled in `userdata`"));
        assert!(header.contains("undefined behaviour"));
    }

    #[test]
    fn generated_host_header_documents_the_async_checkpoint() {
        let header = render().expect("render host header");
        assert!(header.contains("subscript_rt_ctx_async_pending"));
        assert!(header.contains("subscript_rt_ctx_async_step"));
        assert!(header.contains("subscript_rt_ctx_async_unfinished"));
        assert!(
            header.contains("subscript_rt_async_step_report subscript_rt_ctx_async_step_budget(")
        );
        assert!(header.contains("compiler.md` §168"));
        assert!(header.contains("This API is no time limit."));
        assert!(header.contains("Work remains while `pending` is not zero."));
        // The three observers of `compiler.md` §94.2: what a checkpoint can
        // advance, what one checkpoint does, and what stays unfinished.
        assert!(header.contains("runnable continuations"));
        assert!(header.contains("drains the ready queue to\n * empty"));
        assert!(header.contains("started invocations without a completion"));
        assert!(header.contains("On a trapped subscript_rt_context this\n * is a no-op"));
    }

    #[test]
    fn generated_host_header_exposes_and_documents_workers() {
        let header = render().expect("render host header");
        assert!(header.contains("typedef struct subscript_rt_worker subscript_rt_worker;"));
        assert!(header.contains("typedef void (*subscript_rt_worker_entry)("));
        assert!(header.contains("subscript_rt_worker_spawn"));
        assert!(header.contains("subscript_rt_worker_inbox_wait"));
        assert!(header.contains("condition variable and never spins"));
        assert!(header.contains("trap kind 22 (`worker-trapped`)"));
    }

    #[test]
    fn generated_worker_message_descriptor_matches_the_rust_c_layout() {
        let header = render().expect("render host header");
        let descriptor = concat!(
            "typedef struct subscript_rt_worker_message_descriptor {\n",
            "    uint64_t payload_size;\n",
            "    uint64_t string_slot_count;\n",
            "    const uint64_t* string_slot_offsets;\n",
            "} subscript_rt_worker_message_descriptor;"
        );
        assert!(header.contains(descriptor));
        assert_eq!(
            std::mem::offset_of!(WorkerMessageDescriptor, payload_size),
            0
        );
        assert_eq!(
            std::mem::offset_of!(WorkerMessageDescriptor, string_slot_count),
            8
        );
        assert_eq!(
            std::mem::offset_of!(WorkerMessageDescriptor, string_slot_offsets),
            16
        );
        assert_eq!(std::mem::size_of::<WorkerMessageDescriptor>(), 24);
    }

    #[test]
    fn generated_host_header_documents_the_print_observer_contract() {
        let header = render().expect("render host header");
        assert!(header.contains("sink retains none of that line's bytes"));
        assert!(header.contains("valid only for the duration of the callback"));
        assert!(header.contains(
            "must not call any `subscript_rt_*` function taking that subscript_rt_context"
        ));
        assert!(header.contains("aliasing\n * violation and undefined behaviour"));
    }

    #[test]
    fn generated_host_header_documents_the_diagnostics_observer_contract() {
        let header = render().expect("render host header");
        assert!(header.contains(
            "#define SUBSCRIPT_RT_DIAGNOSTICS_ADVISORY_CALLBACK_USERDATA_FREE UINT32_C(1)"
        ));
        assert!(
            header.contains("#define SUBSCRIPT_RT_DIAGNOSTICS_ADVISORY_BINDING_COUNT UINT32_C(2)")
        );
        assert!(header.contains("typedef void (*subscript_rt_diagnostics_observer)"));
        assert!(header.contains("advisory does not trap, cancel, or otherwise change the release"));
        assert!(header.contains("must not\n * call back into script"));
        assert!(header.contains("registered-binding check entirely"));
        assert!(header.contains("Re-registering an existing\n * binding identity never advises"));
        assert!(header.contains("The threshold has literal semantics"));
    }

    #[test]
    fn generated_host_header_declares_the_callback_release_guarantee() {
        let header = render().expect("render host header");
        assert!(header.contains(
            "int32_t subscript_rt_ctx_callback_release(subscript_rt_context* ctx, \
             void* registration);"
        ));
        // The guarantee of §111 rule 5, and the two facts a host needs
        // beside it: what the call answers, and what it does not do.
        assert!(header.contains("the host starts no more calls through\n * this registration"));
        assert!(header.contains("Calls that already run can return"));
        assert!(
            header.contains("returns 1 when `registration` is an open registration of\n * `ctx`")
        );
        assert!(header.contains("it changes nothing and returns 0"));
        assert!(header.contains("never reads a pointer that\n * the set does not hold"));
        assert!(header.contains("does not free the userdata"));
    }

    /// §111 rule 5: every yes-or-no result of the header is `int32_t`,
    /// so the header takes no new include.
    #[test]
    fn generated_host_header_declares_no_c_bool() {
        let header = render().expect("render host header");
        assert!(!header.contains("stdbool"));
        let tokens: Vec<&str> = header
            .split(|c: char| !c.is_ascii_alphanumeric() && c != '_')
            .collect();
        assert!(
            !tokens.contains(&"bool") && !tokens.contains(&"_Bool"),
            "the header names a C bool type"
        );
        // The firing control: the reader finds the spellings the header
        // does use, so an empty token list cannot pass this test.
        assert!(tokens.contains(&"int32_t"));
        assert!(tokens.contains(&"stdint"));
    }

    #[test]
    fn generated_host_header_documents_freed_handle_diagnostics_threshold() {
        let header = render().expect("render host header");
        assert!(header.contains("Recommended freed-handle diagnostics retention budget"));
        assert!(header.contains("runtime does\n * not treat this value specially"));
        assert!(header.contains(
            "#define SUBSCRIPT_RT_FREED_HANDLE_DIAGNOSTICS_DEFAULT_MAX_RETAINED_BYTES \
             UINT64_C(1073741824)"
        ));
        assert!(header.contains("requested payload is at least"));
        assert!(header.contains("oldest retained allocations are evicted"));
        assert!(header.contains("bounded by `max_retained_bytes`"));
        assert!(header.contains("guaranteed for the most\n * recently retained frees"));
        assert!(header.contains("within the class\n * covered by the threshold"));
        assert!(header.contains("and best-effort otherwise"));
        assert!(header.contains("zero budget retains\n * nothing"));
        assert!(header.contains("`UINT64_MAX` is effectively unbounded"));
        assert!(header.contains("`max_retained_bytes` are ignored when `enabled` is 0"));
        assert!(!header.contains("grow without bound"));
        assert!(header.contains("setting is disabled by default"));
    }
    #[test]
    fn runtime_only_header_leaves_program_names_to_the_checker() {
        let runtime = super::render().unwrap();
        assert!(runtime.contains("subscript_rt_ctx_new(void)"));
        assert!(runtime.contains("void subscript_init("));
        assert!(!runtime.contains("void subscript_export_main("));
    }
}
