/* DO NOT EDIT. Generated by subscript-codegen from the checked program. */
#ifndef SUBSCRIPT_ALLOCATION_METADATA_H
#define SUBSCRIPT_ALLOCATION_METADATA_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    uint32_t class_id;
    const char *name;
} subscript_alloc_class_info;

typedef struct {
    const char *file;
    uint32_t line;
    uint32_t column;
} subscript_alloc_position_info;

extern const subscript_alloc_class_info subscript_alloc_classes[];
extern const uint64_t subscript_alloc_class_count;
extern const subscript_alloc_position_info subscript_alloc_positions[];
extern const uint64_t subscript_alloc_position_count;

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* SUBSCRIPT_ALLOCATION_METADATA_H */
